### ISSUE TITLE
@import Firebase not found

### ISSUE THREAD

**Issue by jobert21** [chemerisuk/cordova-plugin-firebase-analytics#101]
I needed to change 
`@import Firebase;` to `#import "Firebase.h"` to build successfully. Any news on this issue?

**Comment by thomasblom** [comment]
Thanks, this fixed my issue!

**Comment by l3vick** [comment]
Do I need every time to import it manually if I delete the platform? Is there any way to no to do this manually?

**Comment by thanhphamtien1** [comment]
even with @jobert21 solution i couldn't make it works... Any idea on this issue :(

**Comment by saberprashant** [comment]
Hey @jobert21 , did you find any solution to that?

**Comment by Sampson8x** [comment]
I am getting the @import Firebase not found exception. @jobert21 Solution doesn't work for me. I'm on cordova-ios@5.0.1

**Comment by daviesdoclc** [comment]
Upgrading to cocoapods 1.8.3 seems to have fixed this for me (without having to modify the plugin)
