### ISSUE TITLE
undefined is not an object (evaluating 'window.plugins.firebase.analytics')

### ISSUE THREAD

**Issue by willnix86** [chemerisuk/cordova-plugin-firebase-analytics#105]
I get the same when using cordova.plugins.firebase...

	window.plugins.firebase.analytics.setEnabled(true) is fired from an init function but I get the following error:

ERROR: Error initializing the application in main. Error: undefined is not an object (evaluating 'window.plugins.firebase.analytics')

What am I doing wrong? How do I actually add this to my project so that it actually works? The read me was a little lax in that regard.

**Comment by chemerisuk** [comment]
Try reinstall the plugin

**Comment by willnix86** [comment]
Re-opening this issue as I still get the same 'undefined' error.

Plugins are all called after deviceready:

````html
<script type="text/javascript">
      window.onload = function() {
        document.addEventListener('deviceready',function(){
          require(['js/main'], function (Main) {
            Main.init();
            document.addEventListener('resume', () => Main.clearBadges(), false);
            document.addEventListener('active', () => Main.clearBadges(), false);
          });
        },false);
      };
    </script>
````

**Comment by willnix86** [comment]
It seems like the js-module part of the plugin.xml isn't being merged as it should.

````javascript
 <js-module src="www/FirebaseAnalytics.js" name="FirebaseAnalytics">
        <merges target="cordova.plugins.firebase.analytics" />
 </js-module>
````
I've tried changing it to the following, then removing re-adding, and building the platform (iOS, in this case), but still nothing.

````javascript
 <js-module src="www/FirebaseAnalytics.js" name="FirebaseAnalytics">
        <clobbers target="firebase.analytics" />
 </js-module>
````

Something I did notice is that, in XCode, under plugins, I don't see the Firebase .h or .m files like I see with all the other plugins. Any thoughts on that?

**Comment by willnix86** [comment]
Another thing I've just noticed is that the plugins are missing from the cordova_plugins.js file in the platform/ios/www folder, so it looks like they aren't being installed onto the platform properly - I have to wait for the platform to build (as it does successfully with other plugins) then add these cordova-plugin-firebase via 'cordova plugin add' separately afterwards

**Comment by martinlyder** [comment]
I have the exact same problem. Running Phonegap 8.2.2 and found that when installing the plugin, i get this error (didn't see it first because it looks like the plugin is installed i the plugins list) : 
```
Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=9.0.0
Skipping 'cordova-plugin-firebase-analytics' for ios

```
So the plugin requires Cordova version above 9, but Phonegap's version is 8.1.1.

**Comment by sotano42** [comment]
> Try reinstall the plugin

Hi, I'm trying to use this plugin but I'm also getting the undefinded error... I did some testing just to try to find out if the namespace is being imported correctly and it seems that when adding the platform I have to uses clobber tag to force the namespace. 

One important thing I noticed is that namespace: **cordova.plugins.firebase.analytics** is not supported, so as soon as I changed it to a shortername with no periods to delilmit its scope, just as a global variable, the plugin found the references correctly.

If you could please apply these changes in to the main thread to work with the plugin it will be greatly appreciated.

**Comment by mobileDev2020** [comment]
Hello,
I am still getting this undefined error using window.plugins.firebase.analytics .
Has anyone gotten this resolved ?

TIA!

**Comment by terreng** [comment]
Same issue here. Doesn't look like the plugin is being installed properly.

**Comment by fra-smw** [comment]
Same here

**Comment by andruli** [comment]
I'm having the same issue on IOS as well. It does work well on Android though.

**Comment by willnix86** [comment]
Any updates on this?

**Comment by nocodedweb** [comment]
Same here.  Any updates?

**Comment by awuge** [comment]
undefined is not an object (evaluating 'window.plugins.firebase.analytics') ；
How did it work out？？？

**Comment by willnix86** [comment]
It didn’t - went with another plugin

**Comment by mobileDev2020** [comment]
Another firebase plugin that works for iOS ?Which one ?

**Comment by willnix86** [comment]
https://github.com/arnesson/cordova-plugin-firebase

**Comment by willnix86** [comment]
It allows for both analytics AND push notifications (messaging), so I’ve only needed to use the one plugin :-)

**Comment by mobileDev2020** [comment]
Has anyone been able to build this on phonegap, will be attempting myself today...

**Comment by mobileDev2020** [comment]
@willnix86 , this worked for me for analytics , I do not have any other firebase features like push or notifications in my app.

https://github.com/freefiona85/cordova-plugin-firebase

**Comment by 50l3r** [comment]
`Cannot read property 'analytics' of undefined`

Same problem using 9.0.0 (cordova-lib@9.0.1) and  Cordova android 8.1.0

I love this plugins. Days and days searching a solution to finish referenced to another plugin 🤣🤣

Thats not my first time. I came from https://github.com/chemerisuk/cordova-plugin-firebase-authentication

The unique powerup for this plugins is our SEO. Sorry if i look unfriendly
