### ISSUE TITLE
Build iOS Error: Use of undeclared identifier 'FIRAnalyticsConfiguration' FirebaseAnalyticsPlugin.m

### ISSUE THREAD

**Issue by Stefan39** [chemerisuk/cordova-plugin-firebase-analytics#106]
Hi,

I have create an App with Ionic and the cordova plugins. On the App version before all works fine (build for ios last time a week ago, for android on saturday) and today after 
```
ionic cordova plugin save
ionic cordova platform rm ios
ionic cordova platform add ios
```
because i have change the App Name in config.xml I got this error on Xcode Build:

[...]/platforms/ios/[App_Name]/Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:48:7: Use of undeclared identifier 'FIRAnalyticsConfiguration'

Before I build it I have do the following in the platform directory:

```
pod install
```

After that i have edited the Podfile:

from
```
platform :ios, '7.0'
target 'App Name' do
	pod 'Firebase/Core', '~> 5.6'
end
```

to 
```
platform :ios, '8.1'
target 'App Name' do
	pod 'Firebase/Core'
end
```
and again in the directory platform/ios:
`pod update`

and open the projectname.xcwordspace in xcode. After that I have imported the GoogleServices.plist in the root directory of the project in xcode and build the app. Here comes the above error.

What can i do?

**Comment by chemerisuk** [comment]
@Stefan39 remove pod 'Firebase/Core' from podfile and reinstall the plugin. You should avoid changing any file manually.

**Comment by Stefan39** [comment]
@chemerisuk Ok thanks... this works. I have change it before because i have got the error code 65 to build the app in iOS and after this changing it works.

But for now, after change Podfile to
```
platform :ios '8.1'
target 'App Name' do
end
```

and 
```
ionic cordova plugin remove cordova-plugin-firebase-analytics
ionic cordova plugin add cordova-plugin-firebase-analytics
ionic cordova build ios --prod
```
the build in xcode works fine.

**Comment by hvaughan3** [comment]
I am using a forked version of this library which includes the Google Tag Manager pod. With versions 7.1.2 and 7.1.3, the GTM pods now depend on newer version of the Firebase pods, which was causing this error.

For now, we specifically target GTM Pod version 7.1.1 until we are ready to update everything.
