### ISSUE TITLE
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: >=5.0.0

### ISSUE THREAD

**Issue by Stefan39** [chemerisuk/cordova-plugin-firebase-analytics#108]
Hm, yesterday i have pushed a new version of my app to ios which was working fine.

Today on build by xcode i got the error, that's firebase analytics are not installed. So i have try to install it with cordova and got this error now?

> cordova plugin add cordova-plugin-firebase-analytics --save
Plugin "cordova-plugin-firebase-analytics" already installed on android.
Installing "cordova-plugin-firebase-analytics" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: >=5.0.0
Skipping 'cordova-plugin-firebase-analytics' for ios

**Comment by chemerisuk** [comment]
cordova-ios v5 is required for version 2

**Comment by Stefan39** [comment]
Ok,

now i have do following:
```
ionic cordova platform remove ios
ionic cordova platform add ios@5.0.0
cd platform/ios
pod install
```

If I'm running the command:
```
ionic cordova build ios --prod
```

produce this error:
```
@import Firebase;
 ~~~~~~~^~~~~~~~
1 error generated.

** BUILD FAILED **
```

**Comment by Stefan39** [comment]
How can i fix this?

The alternative is to remove the analytics plugin from ios.

**Comment by alextapia007** [comment]
try adding in the pod file
pod 'Firebase/Core'
and then  pod install
it's work for me

**Comment by alextapia007** [comment]
and dont forget add the GoogleService-Info.plist file

**Comment by Stefan39** [comment]
Ok, before i should remove (an older ticket here, don't know which one)
pod 'Firebase/Core'

Now i have change the podfile to
```
platform :ios, '8.1'
target 'App Name' do
    pod 'Firebase/Core'
end
```

and run pod update the build works fine.

Thanks @alextapia007

**Comment by alemdg** [comment]
Hello, getting this error when adding iOS platform.

ionic cordova platforms add ios@6.1.0 
Unable to load PlatformApi from platform. SyntaxError: Unexpected token ...
Uncaught, unspecified "error" event. (The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.)


regards.
