### ISSUE TITLE
Module 'Firebase' not found

### ISSUE THREAD

**Issue by willnix86** [chemerisuk/cordova-plugin-firebase-analytics#109]
I have both Phonegap-Plugin-Push installed AND cordova-plugin-firebase-analytics.

Everytime I try to build in xCode, the build fails with "Module 'Firebase' not found" in FirebaseAnalyticsPlugin.m

Any thoughts?

Podfile looks like this:

platform :ios, '9.0'

target 'DHSProgram' do
	project 'DHSProgram.xcodeproj'
	pod 'FirebaseMessaging', '~> 2.0.0'
end

Podfile.lock looks like this:

PODS:
  - FirebaseAnalytics (4.2.0):
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseCore (4.0.20):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (2.0.10):
    - FirebaseCore (~> 4.0)
  - FirebaseMessaging (2.0.8):
    - FirebaseAnalytics (~> 4.0)
    - FirebaseCore (~> 4.0)
    - FirebaseInstanceID (~> 2.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - GoogleToolboxForMac/Defines (2.2.1)
  - GoogleToolboxForMac/Logger (2.2.1):
    - GoogleToolboxForMac/Defines (= 2.2.1)
  - "GoogleToolboxForMac/NSData+zlib (2.2.1)":
    - GoogleToolboxForMac/Defines (= 2.2.1)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - Protobuf (3.7.0)

DEPENDENCIES:
  - FirebaseMessaging (~> 2.0.0)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - FirebaseAnalytics
    - FirebaseCore
    - FirebaseInstanceID
    - FirebaseMessaging
    - GoogleToolboxForMac
    - nanopb
    - Protobuf

**Comment by willnix86** [comment]
Changing @import Firebase; to #import "Firebase.h" didn't work for me

**Comment by wilsolutions** [comment]
Interesting, I've updated my plugin and now I'm getting the same error:

```
Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:3:9: fatal error: module 'Firebase' not found
```

**Comment by chemerisuk** [comment]
@wilsolutions any errors in your install log?

**Comment by wilsolutions** [comment]
Hi @chemerisuk, I don't see, however it work's fine when I am using node 8 😱 
Once I switched to node 9, remove platforms, plugins and node_modules folder and rebuild then it throws the error...
I do the same steps using node 8 and it is fine :P
I'm trying to figure out the relation...

**Comment by juananxt** [comment]
Hi. I have the same problem with v2.0.2.
I need go back to version 1.1.1.

**Comment by chemerisuk** [comment]
I've forced cordova >= 9.0.0 in v2.0.4
