### ISSUE TITLE
Error: cannot find symbol method setCurrentScreen

### ISSUE THREAD

**Issue by GabrielOtero** [chemerisuk/cordova-plugin-firebase-analytics#11]
I got a wierd error when trying to build

I dont know if I am making some mistake or the error really happen

The way i found to can build the project was comment this methos, once e dont need it :)

<img width="1224" alt="screen shot 2016-12-02 at 23 47 27" src="https://cloud.githubusercontent.com/assets/2881903/20855814/b47b8b64-b8e9-11e6-9e95-046f91aa7b10.png">

**Comment by FdezRomero** [comment]
I'm using `setCurrentScreen` on Android and it builds and works correctly. Maybe you are using an older version of the Firebase package from another plugin?

**Comment by GabrielOtero** [comment]
I dont think so.

I've created a new ionic project with 
$ ```ionic start myApp blank ```
$ ```ionic platforms add android``` 
$ ```cordova plugin add cordova-plugin-firebase-analytics --save```
$ ``` ionic build android``` 


and I got same error

**Comment by FdezRomero** [comment]
@GabrielOtero Are you using any other plugins?

**Comment by GabrielOtero** [comment]
No :(

Even with a new projects, just with this plugin, I got the same error.
Could be versions?

Node v4.4.7
Cordova v6.4.0
Ionic v2.1.14

**Comment by FdezRomero** [comment]
Can you do `cordova plugin ls` and paste the output here?

**Comment by GabrielOtero** [comment]
Sure

<img width="542" alt="screen shot 2016-12-08 at 17 27 20" src="https://cloud.githubusercontent.com/assets/2881903/21024451/af75cc16-bd6b-11e6-98cf-3d07c6a8d4c0.png">

**Comment by FdezRomero** [comment]
Open the Android SDK Manager (you can type `android` in the terminal if it's in your PATH) and check that you have the latest "Android Support Repository" and "Google Repository" under Extras. I believe that will update you to the latest Firebase API binaries.

**Comment by Tarekajaj** [comment]
is this solved?

**Comment by Tarekajaj** [comment]
updating "Android Support Repository" and "Google Repository"  solved the issue

**Comment by GabrielOtero** [comment]
I've solved by 

$```cordova platform remove android```
$```cordova platform add android@6.0.0```


Thanks for support :D

**Comment by chemerisuk** [comment]
I believe your warm words should go to @FdezRomero :)

**Comment by msoler95** [comment]
Upgrading capacitor-community/firebase-analytics to 0.3.3 solved the problem :)
