### ISSUE TITLE
can't see any logged events on my firebase console account.

### ISSUE THREAD

**Issue by hamzadev7** [chemerisuk/cordova-plugin-firebase-analytics#112]
I have some issues with using this plugin.

Here is my code snippet.

cordova.plugins.firebase.analytics.logEvent("Share Post", {page: "Email", link: gArticle.link}).then((res) => alert(JSON.stringify(res)))
.catch((error) => alert(JSON.stringify(error)));

I did all proper configurations on my firebase console account and have google-services.json and GoogleService-Info.json files on the root folder of my cordova app.

When I run the app, I always get "OK" as a response(no error) but I can't see any logged events on my firebase console. Is there any idea for fixing this issue?

Thanks in advance.

**Comment by chemerisuk** [comment]
@hamzadev7 try to update to the latest version. Version 6.0 of iOS analytics had issues with logging custom events.

https://firebase.google.com/support/release-notes/ios#6.1.0

**Comment by hamzadev7** [comment]
It also doesn’t work for android.
Here is my steps.

Add Cordova library,
Create new project on firebase console.
Make iOS and android app, download plist file and json file.
Copy them to the root folder of my Cordova project.

Cordova.plugins.firebase.analytics.setEnabled(true);
Cordova.plugins.firebase.analytics.logEvent(“Share Post”, {page: “Email”, link: gArticle.link<http://gArticle.link>});

But after running the app, I checked my firebase console but there weren’t any logged event.
What should I do?


On May 28, 2019, at 4:07 AM, Maksim Chemerisuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@hamzadev7<https://github.com/hamzadev7> try to update to the latest version. Version 6.0 of iOS analytics had issues with logging custom events.

https://firebase.google.com/support/release-notes/ios#6.1.0

**Comment by hamzadev7** [comment]
Switching to cordova-plugin-firebase now.
Thanks

On May 28, 2019, at 4:07 AM, Maksim Chemerisuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@hamzadev7<https://github.com/hamzadev7> try to update to the latest version. Version 6.0 of iOS analytics had issues with logging custom events.

https://firebase.google.com/support/release-notes/ios#6.1.0

**Comment by kerrydp** [comment]
Having this problem also.  Running v2.0.3 and no events are showing up after supposedly triggering them in the iOS simulator.

**Comment by Franco-Alejandro** [comment]
Hello! I'm having issues on android as well. I did all the proper setup of my analytics console and started the tracker on my app component.
After tracking the view "test" and the event "test" in there, I've tried calling the plugin instance in numerous ways to log other events and views, and even when I get the success call I can't see it on my analytics board.

**Comment by JMRMourao** [comment]
Hello,

I am also having this issue, but Ionic 3 application with ionic native 4. the promises always return in 'then' but the response comes as null. Anyone with the same problem?

**Comment by evezzaro** [comment]
Hi guys, is there any news about this? thanks

**Comment by Franco-Alejandro** [comment]
We ended up using google analytics instead of this, and it's working great. Although it would've been nice to be able to use Firebase's analytics...

**Comment by kleeb** [comment]
Google Analytics is deprecated for native apps and will stop collecting events by the end of October.

**Comment by Franco-Alejandro** [comment]
@kleeb oh, could you refer me to the source for this? I'd like to read more about this news. I wasn't able to find something using google.

**Comment by kleeb** [comment]
https://support.google.com/firebase/answer/9167112

**Comment by JMRMourao** [comment]
But our application if its using this plugin is a hybrid app, so it shouldnt be totally affected, unless the profile was in GA was created as a mobile app, correct? but if we change to a new account configured as a web app it should continue working? If anyone could clarify i would be highly appreciated

**Comment by kleeb** [comment]
@JMRMourao it depends how do you use Google Analytics
they are deprecating their SDK, so if you use cordova-plugin-google-analytics it will stop working.

**Comment by maxakash** [comment]
You should remove spaces from name of custom event , should use like "Share_Post" and it would start to show in firebase analytics
