### ISSUE TITLE
Help wanted: Cannot read property analytics of undefined

### ISSUE THREAD

**Issue by savaryt** [chemerisuk/cordova-plugin-firebase-analytics#115]
Hello,

I'm using angular ionic with this plugin.
`cordova.firebase.analytics.logEvent()` doesn't allow compile since cordova is undefined.
So I used:
`windows['plugins'].firebase.analytics.logEvent() `since I'm using this synthax with onesignal but it doesn't work.
`window['cordova'].plugins.firebase.analytics.logEvent` doesn't work.
`window['cordova'].firebase.analytics.logEvent` doesn't work either.
In all case it says that it's undefined.
Any ideas of how I'm supposed to use this package with angular ionic ?

**Comment by savaryt** [comment]
Plugin didn't installed correctly since I am using cordova@6.3.0

**Comment by pilz97** [comment]
@savaryt which cordova-android version are you using to fix the problem?

**Comment by 50l3r** [comment]
Same problem 

I use 9.0.0 (cordova-lib@9.0.1)

**Comment by mitulptridhyatech** [comment]
Any Solution?

**Comment by vdias38** [comment]
Works with cordova.**plugins**.firebase.analytics.logEvent()
