### ISSUE TITLE
Installing plugin doesn't update the Podfile

### ISSUE THREAD

**Issue by epetre** [chemerisuk/cordova-plugin-firebase-analytics#116]
Installing the plugin (latest version) doesn't update the Podfile.
We are using the latest version of the cordova ios platform too.

![Podfile not updated](https://i.gyazo.com/fe7d683ffca207ef9a3eba5a60b301d8.png)

![No error in the logs](https://i.gyazo.com/bf1d6795760ff7ed0784a70ef941ea8f.png)

I had to uninstall the plugin to test if there was a compatibility issue with OneSignal and removed the pods manually. After this I am unable to add them back automatically.

I tried reinstalling the platform, reinstalling the plugin with no luck.

**Comment by epetre** [comment]
I added it manually by copying how the source code here is supposed to do it:

`pod 'Firebase/Analytics', '6.1.0'` and ran 
`pod update` and `pod install`

And it works, it's just weird that adding the plugin doesn't seem to do it automatically.

**Comment by chemerisuk** [comment]
@epetre what cordova-cli version you use?

**Comment by chemerisuk** [comment]
I've forced cordova >= 9.0.0 in v2.0.4

**Comment by epetre** [comment]
it's 8.1.2 `(cordova-lib@8.1.1)` that was the problem then I guess.

**Comment by jvcjunior** [comment]
Hey @epetre how dd you fixed your problem? Just updated to version >= 9.0.0?

**Comment by epetre** [comment]
> Hey @epetre how did you fix your problem? Just updated to version >= 9.0.0?

By updating the cordova-cli to 9+
