### ISSUE TITLE
Cordova version 9.0.0

### ISSUE THREAD

**Issue by AndrsDev** [chemerisuk/cordova-plugin-firebase-analytics#117]
**Error:** 
Installing "cordova-plugin-firebase-analytics" for android
Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=9.0.0

I´m using **Ionic**, the latest cordova version of Ionic is 8.1.1, so... how can I update it?

**Comment by chemerisuk** [comment]
@AndrsDev ask ionic team.
