### ISSUE TITLE
Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by martinnett** [chemerisuk/cordova-plugin-firebase-analytics#119]
I've setup everything on my ionic project and it works well on iOS devices. Unfortunately, it didn't work when I built android, I met some issues and solved a lot, but for this one I'm totally stuck. I hope anyone met this before and can help me, I'll appreciate.

<img width="1088" alt="WX20190712-092636@2x" src="https://user-images.githubusercontent.com/24365284/61095818-90e55680-a487-11e9-9108-9e2346d7eeb7.png">

<img width="838" alt="image" src="https://user-images.githubusercontent.com/24365284/61095865-cbe78a00-a487-11e9-96f3-f28be675d6b7.png">

**Comment by chemerisuk** [comment]
Version 3 uses AndroidX dependencies, try to install version 2:
```
npm i cordova-plugin-firebase-analytics@^2
```

**Comment by martinnett** [comment]
> Version 3 uses AndroidX dependencies, try to install version 2:
> 
> ```
> npm i cordova-plugin-firebase-analytics@^2
> ```

Thanks for the tips, @chemerisuk. But when I tried `npm i cordova-plugin-firebase-analytics@^2`, I got a package not found error, then I tried `npm i cordova-plugin-firebase-analytics@2.0.0` it worked for installation.

After that I rebuild the android app, it built successfully. Then I did the last step which need add firebase SDK like the following instruction:

![image](https://user-images.githubusercontent.com/24365284/61261567-d0c47a80-a7b4-11e9-8541-e065c32818f9.png)

I got a error 

```
Cannot add extension with name 'googleServices', as there is an extension already registered with that name.
```

I found it because I added this line `apply plugin: 'com.google.gms.google-services'`. When I remove that, it still showed up more errors. Then I got lost.

**Comment by chemerisuk** [comment]
@martinnett this gradle plugin added for you automatically, you don't need to change files manually

**Comment by khoabuidev** [comment]
I have the same problems like @martinnett, I have to downgrade to version 2.0

**Comment by florianmonfort** [comment]
> @martinnett this gradle plugin added for you automatically, you don't need to change files manually

If we do that the app just crashes actually....

**Comment by davidquon** [comment]
Seems to also be fixed by doing something similar to what is described here https://github.com/arnesson/cordova-plugin-firebase/issues/1081#issuecomment-503135862.

When I added these everything seems to play nice together using Version 3 with Android X dependencies.
```
$ ionic cordova plugin add cordova-plugin-androidx
$ ionic cordova plugin add cordova-plugin-androidx-adapter
```

**Comment by florianmonfort** [comment]
@davidquon what about in Ionic 4?

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/130
