### ISSUE TITLE
How do we verify that `setScreenName` has set in firebase?

### ISSUE THREAD

**Issue by abhishek3999** [chemerisuk/cordova-plugin-firebase-analytics#120]

**Comment by alextapia007** [comment]
go to events, an then click on screen view
![Captura de pantalla 2020-02-27 a las 9 55 16 a m](https://user-images.githubusercontent.com/15269078/75460606-472e7b00-5947-11ea-9308-82b445e6f191.png)
then select firebase_screen
![Captura de pantalla 2020-02-27 a las 9 56 37 a m](https://user-images.githubusercontent.com/15269078/75460773-7cd36400-5947-11ea-9665-b47ba5af3ae0.png)
now you can see the screens 
![Captura de pantalla 2020-02-27 a las 9 58 17 a m](https://user-images.githubusercontent.com/15269078/75460942-b4daa700-5947-11ea-8d94-d05eac8f9422.png)
