### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'

### ISSUE THREAD

**Issue by mobiemp** [chemerisuk/cordova-plugin-firebase-analytics#121]
Hi, I am using ionic framework.

I want to use this plugin but when i run cordova build, i get the following error:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'

I tried:
cleaning cordova,
removing and re adding android platform,
adding multiDexEnabled true to build.gradle,
updating graddle

If I remove the plugin, everything work normally.

How can I make this plugin work? Thanks

**Comment by davidquon** [comment]
This seems related to https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/123#issuecomment-521440455
