### ISSUE TITLE
"Class not found" error

### ISSUE THREAD

**Issue by thehuangkai** [chemerisuk/cordova-plugin-firebase-analytics#122]
I am using Ionic3 and basically just added the plugin and the ionic native module into the app.

I can run the app and set up firebase analytics no problem, but when I try to log and event using this:

    this.fba.logEvent('page_view', {page: "dashboard"})
    .then((res: any) => console.log(res))
    .catch((error: any) => console.error(error));

I get an error "Class not found".

This error don't provide any helpful information for me to debug

**Comment by chemerisuk** [comment]
Ask ionic team.

**Comment by AB91189** [comment]
> I am using Ionic3 and basically just added the plugin and the ionic native module into the app.
> 
> I can run the app and set up firebase analytics no problem, but when I try to log and event using this:
> 
> ```
> this.fba.logEvent('page_view', {page: "dashboard"})
> .then((res: any) => console.log(res))
> .catch((error: any) => console.error(error));
> ```
> 
> I get an error "Class not found".
> 
> This error don't provide any helpful information for me to debug

were you able to resolve this?
