### ISSUE TITLE
iOS missing event parameters.

### ISSUE THREAD

**Issue by epetre** [chemerisuk/cordova-plugin-firebase-analytics#124]
in iOS only, tracked events are missing some parameters and it's not always the same and it doesn't always happen either.

I'm using the latest version of the plugin 3.0.0 with Cordova 9.0.

1. Sent from the console
![image](https://user-images.githubusercontent.com/1010282/63447482-19053700-c40a-11e9-900e-107672370cd4.png)

2. In the XCode console
![image](https://user-images.githubusercontent.com/1010282/63447515-28848000-c40a-11e9-8a10-32bf43ba054d.png)

3. Sometimes no parameters at all
![image](https://user-images.githubusercontent.com/1010282/63447552-3afeb980-c40a-11e9-91d0-2f44712b84d0.png)

4. Sometimes some paramaters are there
![image](https://user-images.githubusercontent.com/1010282/63447579-45b94e80-c40a-11e9-87f9-651a8ed99736.png)

5. Often, all parameters are present
![image](https://user-images.githubusercontent.com/1010282/63447713-7ac5a100-c40a-11e9-9f2f-1af8407b4739.png)

I can't make sense of this. It looks like an issue that might not be caused by this plugin directly but is deeper in Firebase.

It looks so basic that I'm surprised no one else reported it.

**Comment by hvaughan3** [comment]
I think this may be a bug with the Firebase console debug site. I see the same issue using a different plugin written in an entirely different language so it is not specific to this plugin. You may want to query the BigQuery DB to verify that all your parameters are being recorded correctly.

**Comment by epetre** [comment]
Oh thank you. Checking the BigQuery DB is what lead me there in the first place, we had some parameters that had the wrong type of data in BigQuery, so I investigated with the debug view and assumed that the missing params were the cause.

OK, I think you are right because I reproduced with Android too, I'll open a ticket with the Firebase team.

Thanks @hvaughan3

**Comment by maxakash** [comment]
I am facing this issue in android too.
Is there any workaround?
@epetre

**Comment by maxakash** [comment]
Did you find any solution @epetre ?

**Comment by epetre** [comment]
> Did you find any solution @epetre ?

It turned out to be a bug with the debug view, but the actual events were all correctly sent to Firebase and then to BigQuery.
