### ISSUE TITLE
Google Tag Manager Support

### ISSUE THREAD

**Issue by wilsolutions** [chemerisuk/cordova-plugin-firebase-analytics#125]
Hi Dear,

Any plans to add Google Tag Manager to the project?

Thank you

**Comment by wilsolutions** [comment]
Hi, please, any update on this?
I was thinking about something like this offered by Firebasex:
https://github.com/dpa99c/cordova-plugin-firebasex#google-tag-manager

Thank you

**Comment by hvaughan3** [comment]
We got it working using a fork of this plugin. Checkout the GTM related commits under this branch (a few commit down from the top):

https://github.com/hvaughan3/cordova-plugin-firebase-analytics/commits/master

**Comment by chemerisuk** [comment]
@wilsolutions @hvaughan3 better to implement it as a separate plugin that depends on this one. Not everyone uses GTM.
