### ISSUE TITLE
Adobe phonegap not working

### ISSUE THREAD

**Issue by maximovalexei** [chemerisuk/cordova-plugin-firebase-analytics#127]
Example config.xml:
```
<preference name="phonegap-version" value="cli-7.1.0" />
<plugin name="cordova-support-google-services" source="npm"  />
<plugin name="cordova-plugin-firebase-analytics" source="npm" />
<platform name="android">
    <resource-file src="google-services.json" target="app/google-services.json" />
</platform>
<platform name="ios">
	<resource-file src="GoogleService-Info.plist" />
</platform>
```

GoogleService-Info.plist and google-services.json at the same level as config.xml

window.plugins not firebase plugin. 
cordova.plugins undefined.

Please, help me to configure the plugin for your project adobe phonegap.

**Comment by martinlyder** [comment]
Phonegap supports cordova 8.1.1 this plugin version only accepts 9.0.0 and above, so think its not even installed in your app...

**Comment by Heshyo** [comment]
You can use `cli-9.0.0` instead of `cli-7.1.0` for Cordova iOS 5.0.1 and Cordova Android 8.0.0

**Comment by phiasco12** [comment]
> You can use `cli-9.0.0` instead of `cli-7.1.0` for Cordova iOS 5.0.1 and Cordova Android 8.0.0

I have this in my config.xml file and still cannot install the plugin:

`<preference name="phonegap-version" value='cli-9.0.0' />`

**Comment by achubutkin** [comment]
You can see build log and find it: 
_Fetching plugin "cordova-plugin-firebase-analytics@3.0.0" via npm
Installing "cordova-plugin-firebase-analytics" at "3.0.0" for android
Plugin doesn't support this project's cordova version. cordova: 7.1.0, failed version requirement: >=9.0.0
Skipping 'cordova-plugin-firebase-analytics' for android_

Same problem https://community.adobe.com/t5/PhoneGap-Build/Phonegap-Build-still-thinks-I-m-using-CLI-7-1-0-even-when-CLI-9/td-p/10630117
And more result for this problem in search by keywords Plugin doesn't support this project's cordova version. cordova: 7.1.0, failed version requirement: >=9.0.0

**Comment by Heshyo** [comment]
It's strange indeed. On Phonegap Build, [cli-9.0.0 is supposed to be using Cordova CLI 9.0.0](https://blog.phonegap.com/cli-9-0-0-support-has-been-added-to-phonegap-build-da92fff6d588), but it seems it's still using 7.1.0, and as always, there's no support from Adobe...

**Comment by sbsbessa** [comment]
I'm having the exact same problem while trying to use cli-9.0.0
The platform confirms the version:
PhoneGap (iOS / Android / Windows)
cli-9.0.0 (5.0.1 / 8.0.0 / 7.0.0)

And then I get this on compilation log:
Plugin doesn't support this project's cordova version. cordova: 7.1.0, failed version requirement: >=9.0.0

**Comment by chemerisuk** [comment]
Sorry guys, but phonegap is deprecated now.

https://cordova.apache.org/announcements/2020/08/14/goodbye-phonegap.html
