### ISSUE TITLE
Error build with ionic 4 :  No matching client found for package name 'io.ionic.starter'

### ISSUE THREAD

**Issue by pdechanoz** [chemerisuk/cordova-plugin-firebase-analytics#128]
I have just created a ionic 4 project and add cordova-plugin-firebase-analytics plugin :

ionic cordova build android :

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'io.ionic.starter'

**Comment by maxakash** [comment]
you should use the same package name as mentioned in the google-services.json as your app package name and this issue will get solved

**Comment by pdechanoz** [comment]
OK, thank's
