### ISSUE TITLE
cannot install the plugin

### ISSUE THREAD

**Issue by phiasco12** [chemerisuk/cordova-plugin-firebase-analytics#129]
I'm using Phonegap build and tried to install the plugin but i get this error:

`Plugin doesn't support this project's cordova version. cordova: 7.1.0, failed version requirement: >=9.0.0`

I have this in my config.xml:

`<preference name="phonegap-version" value='cli-9.0.0' />`

**Comment by cedteg** [comment]
welche Cordova Version nutzt du?
also in der CLI `cordova -v`

**Comment by MitchellBouwman** [comment]
@cedteg His version is 7.1.0.

@phiasco12 You should update your cordova with `npm install cordova -g`. For me 9.0.0 isn't working with the rest of my code. I'm working on 8.1.1. But this plugin wont.

**Comment by cedteg** [comment]
@MitchellBouwman oh my bad.

I test this plugin with 9.0.0 and 8.1.2. But didn´t work in my js Application.

**Comment by cedteg** [comment]
For me it work when I changed the requirement CordovaVersion to >= 8.0.0.

**Comment by Heshyo** [comment]
@phiasco12 It seems you're trying to use Phonegap Build. Have you managed to installed this plugin?

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/127
