### ISSUE TITLE
compatibility issue with phonegap-plugin-push

### ISSUE THREAD

**Issue by evezzaro** [chemerisuk/cordova-plugin-firebase-analytics#130]
Hi guys, I I've been trying to get this plugin to work along with phonegap-plugin-push, but i couldn't get them to work together. Do you guys have any idea on how to resolve this compatibility issue?

System Info:

Ionic:

ionic (Ionic CLI) : 4.12.0 (/Users/elevasrl/.nvm/versions/node/v11.9.0/lib/node_modules/ionic)
Ionic Framework : ionic1 1.3.4
@ionic/v1-toolkit : 1.0.22

Cordova:

cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.0.0, ios 5.0.1
Cordova Plugins : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 36 other plugins)

System:

Android SDK Tools : 26.1.1 (/Users/elevasrl/Library/Android/sdk)
ios-deploy : 1.9.4
ios-sim : 8.0.1
NodeJS : v11.9.0 (/Users/elevasrl/.nvm/versions/node/v11.9.0/bin/node)
npm : 6.9.0
OS : macOS Mojave
Xcode : Xcode 11.0 Build version 11A420a

The output i get on building is this:

Task :app:compileDebugJavaWithJavac FAILED
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushPlugin.java:15: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
^
symbol: class NotificationCompat
location: package android.support.v4.app
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/PushPlugin.java:16: error: cannot find symbol
import android.support.v4.app.NotificationManagerCompat;
^
symbol: class NotificationManagerCompat
location: package android.support.v4.app
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:26: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
^
symbol: class NotificationCompat
location: package android.support.v4.app
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:27: error: package android.support.v4.app.NotificationCompat does not exist
import android.support.v4.app.NotificationCompat.WearableExtender;
^
/Users/elevasrl/Desktop/GITHUB/YachtNeeds-App/platforms/android/app/src/main/java/com/adobe/phonegap/push/FCMService.java:28: error: cannot find symbol
import android.support.v4.app.RemoteInput;

...... MORE ......

Do you guys have any other solutions for this?

Thanks,

**Comment by chemerisuk** [comment]
@evezzaro conflict because version 2 depends on androidX libraries. Try to install version 1  of the plugin.

**Comment by makryl** [comment]
version ^1.1.1 of cordova-plugin-firebase-analytics
version ^1.1.0 of cordova-plugin-firebase-inappmessaging
and setting FCM_VERSION="17.+" for phonegap-plugin-push
solvers dependency problems for me
