### ISSUE TITLE
Events are not logged in Firebase in iOS

### ISSUE THREAD

**Issue by nv-knadarajah** [chemerisuk/cordova-plugin-firebase-analytics#136]
Hello,

I'm using the latest cordova-plugin-firebase-analytics plugin and I did all the necessary configuration for ios but I didn't get any events logged in firebase.

configurations:-
cordova: 9.0.0 (cordova-lib@9.0.1)
phonegap version: 9.0.0

Installed platforms:
  android 8.1.0
  ios 5.0.1

Podfile:

platform :ios, '9.0'

target 'project name' do
	project 'project_name.xcodeproj'
	pod 'OneSignal', '2.8.7'
	pod 'Usabilla', '5.1.2'
	pod 'Firebase/Analytics', '~> 6.3.0'

Added GoogleService-Info.plist in project root folder platforms/ios/Resources/
<resource-file src="GoogleService-Info.plist" />

Enabled FIRAnalyticsDebugEnabled in XCode 10.1 (Swift 4)

Device: iPhone 6 plus (iOS 12.0.1)

The firebase logs in Xcode:-
`2019-11-08 09:51:36.717047-0500 project_name[265:6577] 6.3.0 - [Firebase/Analytics][I-ACS023072] Event logged. Event name, event params: external, {
    click = external;
    firebase_debug (_dbg) = 1;
    firebase_event_origin (_o) = app;
    firebase_screen (_sn) = some_screen;
    firebase_screen_class (_sc) = MainViewController;
    ga_realtime (_r) = 1;
    ga_screen_id (_si) = -4359475130514001107;
}`

It's working fine on Android and I can see screens and events in Firebase.

Did I missed any other configuration?

**Comment by smartsanja2013** [comment]
I am facing the same issue. I have downgraded to cordova-plugin-firebase-analytics@2.0.0 and tried. Still events from ios not logged. Android working fine. @nv-knadarajah did you manage to resolve the issue?

**Comment by nv-knadarajah** [comment]
@smartsanja2013 

Yes, update FirebaseAnalyticsPlugin.m file as in below:-

`//if(![FIRApp` defaultApp]) {
    //    [FIRApp configure];
   // }
    // get GoogleService-Info.plist file path
    NSString *filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist"];
    
    // if file is successfully found, use it
    if(filePath){
        NSLog(@"GoogleService-Info.plist found, setup: [FIRApp configureWithOptions]");
        // create firebase configure options passing .plist as content
        FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
        
        // configure FIRApp with options
        [FIRApp configureWithOptions:options];
    }
    
    // no .plist found, try default App
    if (![FIRApp defaultApp] && !filePath) {
        NSLog(@"GoogleService-Info.plist NOT FOUND, setup: [FIRApp defaultApp]");
        [FIRApp configure];
    }
`
Hope that helps.

**Comment by nichovski** [comment]
@nv-knadarajah is this updated in the latest version on npm? I'm still not able to log ios events.

Thanks

**Comment by ankushbadlas** [comment]
I am facing same issue. From iOS build, I am not able to set user property into cloud messaging. 
Please help me how I can resolve my firebase cloud message with ionic iOS build .

I installed Firebase Analytics from https://www.npmjs.com/package/@ionic-native/firebase-analytics link
I already configured to setup property for firebase analytics like as below code
this.firebaseAnalytics.setUserId("3jskz-znxxkx-xmxx-zznnz99zzx-xxssqqw");
this.firebaseAnalytics.setUserProperty("firstName", "Ank");
this.firebaseAnalytics.setUserProperty("lastName", "Kun");
this.firebaseAnalytics.setUserProperty("email", "ank@gmail.com");
I downloaded GoogleService-info.plist file and placed it in my root directory.
Create build from xcode and signup a user from mobile app.
I am not able see my signup users into firebase cloud message section after filter user property by email and enter email like "ank@gmail.com". It shows me like 0% of potential users are eligible for this campaign: 0

Can anyone help me what I am missing?
