### ISSUE TITLE
Firebase resetAnalyticsData method is not working

### ISSUE THREAD

**Issue by ankitsolanki-multidots** [chemerisuk/cordova-plugin-firebase-analytics#137]
I have install this plugin for analytics and i have follow the step as following link.

https://ionicframework.com/docs/v3/native/firebase-analytics/

But i can not access resetAnalyticsData method for reset analytics data.

```
import { FirebaseAnalytics } from '@ionic-native/firebase-analytics';

constructor(private firebaseAnalytics: FirebaseAnalytics) { }

this.firebaseAnalytics.resetAnalyticsData()
  .then((res: any) => console.log(res))
  .catch((error: any) => console.error(error));
```

Can you please let me know how i can use above method with this plugin?

**Comment by chemerisuk** [comment]
Ask ionic team.
