### ISSUE TITLE
Custom events not captured in Android release build

### ISSUE THREAD

**Issue by guanghong-ds** [chemerisuk/cordova-plugin-firebase-analytics#139]
Hi,

I facing some issue on android release build. All the function ( setScreenName, logEvent... ) is not capture in the Analytics. But on the debug build it works fine, have you face similar issue with release build?

I did try to off the minify it does not work.

Below is the proguard setting I have on google libs,

-keep class com.google.** { *; }
-keep class com.google.analytics.** { *; }
-keepclassmembers class com.google.** { *; }
-keepclassmembers class com.google.analytics.** { *; }
-dontwarn com.google.common.**
-dontwarn com.google.ads.**

**Comment by yashbhow** [comment]
I have also encountered this issue and solved this by adding these two lines in pro-guard file.

-keep class by.chemerisuk.cordova.firebase.** { *; }
-keep class by.chemerisuk.cordova.support.** { *; }

**Comment by chemerisuk** [comment]
Add all rules from the section below:

https://github.com/chemerisuk/cordova-support-android-plugin#proguard-notes

**Comment by Adm94** [comment]
Hi,
Do we have to install proguard ?
I have this issue but I do not use proguard.
