### ISSUE TITLE
Missing documentation how to use this with Typescript (ionic 2)

### ISSUE THREAD

**Issue by RoelRoel** [chemerisuk/cordova-plugin-firebase-analytics#14]
Are there Typescript typings available?
Now i'm getting a lot of Property 'cordova' does not exist on type 'Window' errors when trying to call window.cordova.plugins.firebase.analytics.*

**Comment by FdezRomero** [comment]
Use `declare var window;` after your imports and Typescript won't complain anymore about properties inside window.

**Comment by Cempakers87** [comment]
@FdezRomero I use ionic 2 as well and have already followed your suggestion. When I build and emulate my project, there is no error. But if I run command `ionic serve`, it getting error like: 
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'plugins' of undefined

Please help.

**Comment by FdezRomero** [comment]
@Cempakers87 that's because Cordova plugins normally don't run in the browser (there are a few exceptions).

It's good practice when you are using any plugin to check if the app is running in Cordova and that has initialized. Wrap your calls like this (assuming you already imported and injected `Platform` in the constructor):

```ts
if (this.platform.is('cordova')) {
  this.platform.ready().then(() => {
    // Put your plugin calls here
  });
}
```

**Comment by RoelRoel** [comment]
But I'm using Typescript for a reason. I want to be able to use types. How to use the typings/cordova-fabric-plugin.d.ts file in an Ionic project?

**Comment by oddcb** [comment]
You are probably aware, but this plugin has been added to Ionic Native, so typings are available if you add the Ionic Native plugin. 

http://ionicframework.com/docs/native/firebase-analytics/
