### ISSUE TITLE
No longer add the Android library com.google.firebase:firebase-core.

### ISSUE THREAD

**Issue by wilsolutions** [chemerisuk/cordova-plugin-firebase-analytics#141]
Hi, with the latest release (com.google.firebase:firebase-core:17.2.2), Firebase asks to "No longer add the Android library com.google.firebase:firebase-core.".

I'm wondering to know how this affect the plugin and if do we have a plan to update it.

https://firebase.google.com/support/release-notes/android#latest_sdk_versions

Thank you

**Comment by chemerisuk** [comment]
@wilsolutions upgrade to v4
