### ISSUE TITLE
Can not build the cordova app after installing this plugin

### ISSUE THREAD

**Issue by vikk** [chemerisuk/cordova-plugin-firebase-analytics#143]
error code for: cordova -d build

`> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dexarchives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
36 actionable tasks: 2 executed, 34 up-to-date
Command finished with error code 1: C:\Users\vikkesz\Documents\testcordova\thecircleuj\platforms\android\gradlew cdvBuildDebug,-b,C:\Users\vikkesz\Documents\testcordova\thecircleuj\platforms\android\build.gradle
C:\Users\vikkesz\Documents\testcordova\thecircleuj\platforms\android\gradlew: Command failed with exit code 1 Error output:
D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dexarchives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Error: C:\Users\vikkesz\Documents\testcordova\thecircleuj\platforms\android\gradlew: Command failed with exit code 1 Error output:
D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dexarchives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
    at ChildProcess.whenDone (C:\Users\vikkesz\Documents\testcordova\thecircleuj\node_modules\cordova-common\src\superspawn.js:135:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\vikkesz\Documents\testcordova\thecircleuj\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)`

**Comment by 814k31** [comment]
@vikk are you overriding the firebase core version?

I have not been able to successfully build with the default (`17.2`) as I always get manifest merger issues which I think have something to do with androidx migration

So my configuration has to be:
package.json
```json
"cordova-plugin-firebase-analytics": {
    "FIREBASE_CORE_VERSION": "16.+"
},
```

config.xml
```xml
<plugin name="cordova-plugin-request-location-accuracy" spec="^2.3.0">
    <variable name="PLAY_SERVICES_LOCATION_VERSION" value="16.+" />
</plugin>
```

**Comment by vikk** [comment]
Using plugins cordova-plugin-androidx an cordova-plugin-androidx-adapter solved my problem.
