### ISSUE TITLE
setUserId() method is overriding the value of Device ID dimension in Exploration reports

### ISSUE THREAD

**Issue by alfaraj** [chemerisuk/cordova-plugin-firebase-analytics#144]
I expect the setUserId() method to use User ID column in Analysis > Exploration, but in my case it is overwriting Device ID values. Is this an expected behavior?! or am I missing something?!

<img width="555" alt="device-id" src="https://user-images.githubusercontent.com/15920516/74714840-6c7f0300-523c-11ea-8f3b-6932695d4795.png">

**Comment by chemerisuk** [comment]
Better to ask firebase team, because I'm just calling SDK method.
