### ISSUE TITLE
Firebase screen name is showing (not set)

### ISSUE THREAD

**Issue by alfaraj** [chemerisuk/cordova-plugin-firebase-analytics#145]
Although I am able to log screen names in the console, I have observed a lot of events that do not record screen name values and showing as "(not set)".

I have used [`setCurrentScreen(name)`](https://github.com/chemerisuk/cordova-plugin-firebase-analytics#setcurrentscreenname) for logging screen view event.

<img width="358" alt="Untitled" src="https://user-images.githubusercontent.com/15920516/74814869-3d829300-5309-11ea-82c7-9ffb3231b09e.png">

![{6C6D2B6B-3DE9-4EA8-938A-B5B93E27E36D} png](https://user-images.githubusercontent.com/15920516/74812753-28a40080-5305-11ea-95b4-a615b71331f4.jpg)

**Comment by vikasshinde448** [comment]
Check this link i hope this link is help you 

https://support.google.com/analytics/answer/2820717?hl=en

**Comment by chemerisuk** [comment]
Not related to the plugin.

**Comment by DeepakSaha1** [comment]
facing this kind of issue in my project. If any one has understand properly what does it mean (not set).
please respond.
Thank you in advance

**Comment by vikasshinde448** [comment]
Check this link i hope this link is help you
https://support.google.com/analytics/answer/2820717?hl=en

[image: Screenshot 2020-07-11 at 4.54.14 PM.png]

**Comment by piyushgupta214** [comment]
> Not related to the plugin.

could you please give some reason, as its not related to the plugin. 
a closed thread without proper reasoning makes this plugin use uncomfortable
