### ISSUE TITLE
Deprecation of install_referrer intent

### ISSUE THREAD

**Issue by wilsolutions** [chemerisuk/cordova-plugin-firebase-analytics#147]
Hi,

I did run in to this issue and I have update the other plugins however I'm still getting this error with the firebase plugin.

https://stackoverflow.com/questions/59274930/install-referrer-intent-deprecation?noredirect=1&lq=1

Any thoughts?
tkx

**Comment by chemerisuk** [comment]
@wilsolutions do you see an issue on the latest version?

**Comment by marc0n3** [comment]
Hi @chemerisuk, one question.
Do this plugin make use of Android install referral or do I have to install other plugins to get referral tracking in my cordova app?
Thanks in advance,
Marco

**Comment by chemerisuk** [comment]
> Do this plugin make use of Android install referral
I doesn't.

**Comment by realrobert28** [comment]
Hi, 
Im currently using the latest version of cordova-plugin-firebase-analytics 4.3.0/4.2.0 and cordova-support-google-services 1.4.0.

Error is 
> 2020-05-05 17:50:46.102 2414-4923/? E/FA-SVC: Service response is missing Install Referrer install timestamp. 

Do you have any idea how to fix this?

Thanks.
