### ISSUE TITLE
LogEvent Not Working on Android

### ISSUE THREAD

**Issue by megatcorleone** [chemerisuk/cordova-plugin-firebase-analytics#148]
I have been curious only Android not working. In Android Studio, I put breakpoint on plugin init, it did break. But on other method e.g logEvent did seem not working also with DebugView on Firebase console. On iOS, breakpoints for all methods and on DebugView are working.

`03/10 13:34:36: Launching 'app' on samsung SM-A920F.
$ adb shell am start -n "com.example.com" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.example.com| com.example.com
Waiting for application to come online: com.example.com | com.example.com
Waiting for application to come online: com.example.com | com.example.com
Connecting to com.example.com
Waiting for application to start debug server
Waiting for application to come online: com.example.com | com.example.com
Connecting to com.example.com
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8601', transport: 'socket'
I/chatty: uid=10986(com.example.com) identical 2 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1310)
I/.com.example.com: The ClassLoaderContext is a special shared library.
V/FA: Registered activity lifecycle callback
I/FirebaseInitProvider: FirebaseApp initialization successful
I/CordovaLog: Changing log level to ERROR(6)
V/FA: onActivityCreated
V/FA: Collection enabled
V/FA: App package, google app id: com.example.com, 1:1017374172086:android:4c4abf09f1febd04b21717
I/FA: App measurement is starting up, version: 16250
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA: Faster debug mode event logging enabled. To disable, run:
      adb shell setprop debug.firebase.analytics.app .none.
D/FA: Debug-level message logging enabled
I/WebViewFactory: Loading com.android.chrome version 73.0.3683.90 (code 368309052)
I/cr_LibraryLoader: Time to load native libraries: 13 ms (timestamps 7388-7401)
I/chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader: Expected native library version number "73.0.3683.90", actual native library version number "73.0.3683.90"
D/INA: DNS Yielder thread is started ... [com.example.com]
W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
W/.com.example.com: Accessing hidden method Landroid/content/Context;->bindServiceAsUser(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/Handler;Landroid/os/UserHandle;)Z (light greylist, reflection)
I/cr_BrowserStartup: Initializing chromium process, singleProcess=false
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
D/ConnectivityManager: requestNetwork; CallingUid : 10986, CallingPid : 30162
D/ConnectivityManager: requestNetwork; CallingUid : 10986, CallingPid : 30162
W/.com.example.com: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
    Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/.com.example.com: Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
    Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
    Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
    Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
    Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
    Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
I/DecorView: createDecorCaptionView >> DecorView@18accf7[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/FirebaseAnalyticsPlugin: Starting Firebase Analytics plugin
D/Dialog: mIsSamsungBasicInteraction = false
    mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/DecorView: createDecorCaptionView >> DecorView@3c953da[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/OpenGLRenderer: Skia GL Pipeline
D/EmergencyMode: [EmergencyManager] android createPackageContext successful
D/InputTransport: Input channel constructed: fd=116
D/ViewRootImpl@a78d3a6[MainActivity]: setView = DecorView@3c953da[MainActivity] TM=true MM=false
D/Dialog: mIsSamsungBasicInteraction = false
    mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/DecorView: createDecorCaptionView >> DecorView@abad3b6[], isFloating: true, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/ScrollView: initGoToTop
D/InputTransport: Input channel constructed: fd=117
D/ViewRootImpl@171ee97[MainActivity]: setView = DecorView@abad3b6[MainActivity] TM=true MM=false
I/CordovaLog: Changing log level to 6
D/GoogleMapsPlugin: ----> checkGooglePlayServices = true
E/MyPluginLayout: --> zoomScale = 2.625
D/ScrollView: initGoToTop
I/zzbz: Making Creator dynamically
W/.ge.sgp.reward: Unsupported class loader
W/.ge.sgp.reward: Skipping duplicate class check due to unsupported classloader
I/DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:222
    Selected remote version of com.google.android.gms.maps_dynamite, version >= 222
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
I/DynamiteLoaderV2: [71] Mapsdynamite
W/.ge.sgp.reward: Unsupported class loader
W/.ge.sgp.reward: Skipping duplicate class check due to unsupported classloader
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
D/NetworkManagementSocketTagger: tagSocket(124) with statsTag=0xffffffff, statsUid=-1
I/Google Maps Android API: Google Play services client version: 12451000
D/Diagnostic: initialize()
D/Diagnostic_Location: initialize()
D/Diagnostic_Camera: initialize()
D/Diagnostic_Notifications: initialize()
I/Adreno: QUALCOMM build                   : 61e74ae, If23bcb88b5
    Build Date                       : 02/27/19
    OpenGL ES Shader Compiler Version: EV031.25.03.00
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.2.R1.09.00.00.442.045
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
    Build Config                     : S L 6.0.7 AArch64
I/Adreno: PFP: 0x005ff112, ME: 0x005ff066
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
W/cr_media: Requires BLUETOOTH permission
D/ViewRootImpl@171ee97[MainActivity]: stopped(false) old=false
D/ViewRootImpl@a78d3a6[MainActivity]: stopped(false) old=false
D/InputTransport: Input channel constructed: fd=134
D/ViewRootImpl@58f71e5[MainActivity]: setView = DecorView@18accf7[MainActivity] TM=true MM=false
D/ConnectivityManager: requestNetwork; CallingUid : 10986, CallingPid : 30162
D/ConnectivityManager: requestNetwork; CallingUid : 10986, CallingPid : 30162
W/AudioCapabilities: Unsupported mime audio/ac4
W/AudioCapabilities: Unsupported mime audio/x-ima
I/FA: Tag Manager is not found and thus will not be used
W/AudioCapabilities: Unsupported mime audio/eac3-joc
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=799287768385800007}]
W/AudioCapabilities: Unsupported mime audio/mpeg-L1
W/AudioCapabilities: Unsupported mime audio/mpeg-L2
W/AudioCapabilities: Unsupported mime audio/x-ms-wma
I/Choreographer: Skipped 76 frames!  The application may be doing too much work on its main thread.
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
V/FA: Activity resumed, time: 697054208
D/ViewRootImpl@a78d3a6[MainActivity]: Relayout returned: old=[0,0][1080,2094] new=[0,0][1080,2094] result=0x7 surface={true 504161599488} changed=true
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
D/OpenGLRenderer: eglCreateWindowSurface = 0x756163c280, 0x75625f8010
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
D/ViewRootImpl@171ee97[MainActivity]: Relayout returned: old=[0,63][1080,2094] new=[1,1968][1079,2094] result=0x7 surface={true 504145276928} changed=true
D/OpenGLRenderer: eglCreateWindowSurface = 0x7564aed980, 0x7561667010
W/VideoCapabilities: Unrecognized profile 4 for video/hevc
W/VideoCapabilities: Unsupported mime video/mp43
W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities: Unsupported mime video/wvc1
W/VideoCapabilities: Unsupported mime video/wvc1
W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
D/ViewRootImpl@58f71e5[MainActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={true 504145281024} changed=true
D/OpenGLRenderer: eglCreateWindowSurface = 0x7564aeda00, 0x7561668010
D/ScrollView:  onsize change changed 
D/ViewRootImpl@a78d3a6[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c953da[MainActivity]
D/InputMethodManager: getNavigationBarColor() -855310
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c953da[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.example.com ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
W/Utils: could not parse long range '175-174'
D/ViewRootImpl@171ee97[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputTransport: Input channel constructed: fd=142
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/.ge.sgp.reward: Explicit concurrent copying GC freed 36170(2001KB) AllocSpace objects, 20(788KB) LOS objects, 68% free, 2MB/8MB, paused 144us total 29.530ms
I/chromium: [INFO:CONSOLE(22)] "The Content-Security-Policy directive 'script-src-elem' is implemented behind a flag which is currently disabled.
    ", source: file:///android_asset/www/index.html (22)
D/ViewRootImpl@a78d3a6[MainActivity]: MSG_RESIZED_REPORT: frame=[0,0][1080,2094] ci=[0,63][0,0] vi=[0,63][0,0] or=1
D/ViewRootImpl@171ee97[MainActivity]: MSG_RESIZED_REPORT: frame=[1,1968][1079,2094] ci=[0,0][0,0] vi=[0,0][0,0] or=1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c953da[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.example.com ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 4
D/ViewRootImpl@a78d3a6[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c953da[MainActivity]
D/InputMethodManager: getNavigationBarColor() -855310
D/ViewRootImpl@58f71e5[MainActivity]: MSG_RESIZED_REPORT: frame=[0,0][1080,2220] ci=[0,63][0,126] vi=[0,63][0,126] or=1
I/chromium: [INFO:CONSOLE(1)] "Angular is running in the development mode. Call enableProdMode() to enable the production mode.", source: file:///android_asset/www/build/vendor.js (1)
V/Native Storage: Init NativeStorage
V/Diagnostic_Location: Location permission is authorized
V/Diagnostic: Get authorisation status for android.permission.ACCESS_COARSE_LOCATION
V/Diagnostic: Get authorisation status for android.permission.ACCESS_FINE_LOCATION
I/chromium: [INFO:CONSOLE(1)] "Ionic Native: deviceready event fired after 2041 ms", source: file:///android_asset/www/build/vendor.js (1)
V/Diagnostic_Location: Location permission is authorized
I/chromium: [INFO:CONSOLE(1)] "ERROR", source: file:///android_asset/www/build/vendor.js (1)
I/chromium: [INFO:CONSOLE(1)] "ERROR", source: file:///android_asset/www/build/vendor.js (1)
I/RootBeer: LOOKING FOR BINARY: /data/local/su Absent :(
    LOOKING FOR BINARY: /data/local/bin/su Absent :(
    LOOKING FOR BINARY: /data/local/xbin/su Absent :(
    LOOKING FOR BINARY: /sbin/su Absent :(
    LOOKING FOR BINARY: /su/bin/su Absent :(
    LOOKING FOR BINARY: /system/bin/su Absent :(
    LOOKING FOR BINARY: /system/bin/.ext/su Absent :(
    LOOKING FOR BINARY: /system/bin/failsafe/su Absent :(
    LOOKING FOR BINARY: /system/sd/xbin/su Absent :(
    LOOKING FOR BINARY: /system/usr/we-need-root/su Absent :(
    LOOKING FOR BINARY: /system/xbin/su Absent :(
    LOOKING FOR BINARY: /cachesu Absent :(
    LOOKING FOR BINARY: /datasu Absent :(
    LOOKING FOR BINARY: /devsu Absent :(
I/chromium: [INFO:CONSOLE(1)] "[object Object]", source: file:///android_asset/www/build/main.js (1)
D/ADBMobile: ADBMobile Debug : Analytics - Request Queued (ndh=1&mid=24796169433333280688225876447882095495&ce=UTF-8&c.&a.&AppID=UPGREAT%20Singapore%203.0.0.0%20%2830000%29&RunMode=Application&OSVersion=Android%209&TimeSinceLaunch=5&Resolution=1080x2094&DeviceName=SM-A920F&.a&.c&t=00%2F00%2F0000%2000%3A00%3A00%200%20-480&pageName=Rewards%20App%20ready%20SG&ts=1583818488)
W/ADBMobile: ADBMobile Warning : Analytics - Unable to save context data (context data was null or empty)
I/chromium: [INFO:CONSOLE(1)] "Setting Flag", source: file:///android_asset/www/build/main.js (1)
V/Push_Plugin: execute: action=hasPermission
D/Push_Plugin: has permission: true
V/Push_Plugin: execute: action=setApplicationIconBadgeNumber
V/Push_Plugin: setApplicationIconBadgeNumber: data=[{"badge":0}]
I/chromium: [INFO:CONSOLE(1)] "We have permission to send push notifications", source: file:///android_asset/www/build/main.js (1)
D/ADBMobile: ADBMobile Debug : Analytics - Request Queued (ndh=1&ce=UTF-8&c.&a.&AppID=UPGREAT%20Singapore%203.0.0.0%20%2830000%29&RunMode=Application&OSVersion=Android%209&action=Lauch&action.&time.&total=0&inapp=0&.time&.action&TimeSinceLaunch=5&Resolution=1080x2094&DeviceName=SM-A920F&.a&.c&t=00%2F00%2F0000%2000%3A00%3A00%200%20-480&pe=lnk_o&pev2=AMACTION%3ALauch&mid=24796169433333280688225876447882095495&pageName=UPGREAT%20Singapore%203.0.0.0%20%2830000%29&ts=1583818488)
V/Push_Plugin: execute: action=init
V/Push_Plugin: execute: data=[{"android":{"senderID":"54271426580","icon":"notification_icon","iconColor":"red","clearBadge":true,"forceShow":true},"ios":{"alert":"true","badge":true,"sound":"false","clearBadge":true},"windows":{}}]
I/chromium: [INFO:CONSOLE(1)] "OK", source: file:///android_asset/www/build/main.js (1)
V/Push_Plugin: execute: jo={"senderID":"54271426580","icon":"notification_icon","iconColor":"red","clearBadge":true,"forceShow":true}
V/Push_Plugin: execute: senderID=1017374172086
V/Push_Plugin: onRegistered: {"registrationId":"cCsVk_03PIY:APA91bGDNm_H07IUUWK4WYUaG5xjGua3UXqwJzDWIsB2r4txzx1H5SOSR9A7QJ5jkuyFxR5JNDPgFun1rCEifHWLfum4v6AvUYJP5OO8RJPLS66GFwmQJecCZDXuaYK2Zns7enU00iFy","registrationType":"FCM"}
I/chromium: [INFO:CONSOLE(1)] "device token", source: file:///android_asset/www/build/main.js (1)
I/chromium: [INFO:CONSOLE(1)] "DEVICE ID", source: file:///android_asset/www/build/main.js (1)
I/RootBeer: LOOKING FOR BINARY: /data/local/su Absent :(
    LOOKING FOR BINARY: /data/local/bin/su Absent :(
    LOOKING FOR BINARY: /data/local/xbin/su Absent :(
    LOOKING FOR BINARY: /sbin/su Absent :(
    LOOKING FOR BINARY: /su/bin/su Absent :(
    LOOKING FOR BINARY: /system/bin/su Absent :(
    LOOKING FOR BINARY: /system/bin/.ext/su Absent :(
    LOOKING FOR BINARY: /system/bin/failsafe/su Absent :(
    LOOKING FOR BINARY: /system/sd/xbin/su Absent :(
    LOOKING FOR BINARY: /system/usr/we-need-root/su Absent :(
    LOOKING FOR BINARY: /system/xbin/su Absent :(
    LOOKING FOR BINARY: /cachesu Absent :(
    LOOKING FOR BINARY: /datasu Absent :(
    LOOKING FOR BINARY: /devsu Absent :(
I/chromium: [INFO:CONSOLE(1)] "YES!!", source: file:///android_asset/www/build/main.js (1)
V/FA: Inactivity, disconnecting from the service
D/ADBMobile: ADBMobile Debug : Analytics - Request Queued (ndh=1&mid=24796169433333280688225876447882095495&ce=UTF-8&c.&a.&AppID=UPGREAT%20Singapore%203.0.0.0%20%2830000%29&RunMode=Application&OSVersion=Android%209&TimeSinceLaunch=6&Resolution=1080x2094&DeviceName=SM-A920F&.a&.c&t=00%2F00%2F0000%2000%3A00%3A00%200%20-480&pageName=Home%20page%20SG&ts=1583818489)
D/OpenGLRenderer: eglDestroySurface = 0x7564aed980, 0x7561667000
D/ViewRootImpl@171ee97[MainActivity]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: fd=117
D/ViewRootImpl@a78d3a6[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3c953da[MainActivity]
D/InputMethodManager: getNavigationBarColor() -855310
E/ViewRootImpl: sendUserActionEvent() returned.
D/OpenGLRenderer: eglDestroySurface = 0x756163c280, 0x75625f8000
D/ViewRootImpl@a78d3a6[MainActivity]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: fd=116
D/ViewRootImpl@58f71e5[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@18accf7[MainActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@18accf7[MainActivity]
D/InputMethodManager: getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.example.com ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=156
    Input channel destroyed: fd=142
E/ViewRootImpl: sendUserActionEvent() returned.
I/.ge.sgp.reward: Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()
I/chromium: [INFO:CONSOLE(1)] "this.advList$.skip(1).subscribe(res => {", source: file:///android_asset/www/build/main.js (1)
D/ViewRootImpl@58f71e5[MainActivity]: ViewPostIme pointer 0
D/ViewRootImpl@58f71e5[MainActivity]: ViewPostIme pointer 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@18accf7[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.example.com ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: fd=168
D/InputTransport: Input channel destroyed: fd=156
D/InputMethodManager: HSIFW - flag : 0 Pid : 30162
D/InputMethodManager: HSIFW - flag : 0 Pid : 30162
D/ViewRootImpl@58f71e5[MainActivity]: ViewPostIme pointer 0
D/ViewRootImpl@58f71e5[MainActivity]: ViewPostIme pointer 1
D/InputMethodManager: HSIFW - flag : 0 Pid : 30162
D/InputMethodManager: HSIFW - flag : 0 Pid : 30162
D/CordovaBranchSDK: Execute: initSession
D/CordovaBranchSDK: Runnable: initSession
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger: tagSocket(151) with statsTag=0x66, statsUid=-1
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/NetworkManagementSocketTagger: tagSocket(156) with statsTag=0x0, statsUid=-1
I/chromium: [INFO:CONSOLE(1)] "[object Object]", source: file:///android_asset/www/build/main.js (1)
I/chromium: [INFO:CONSOLE(1)] "SUCCESSSSSS saveMetricByBatch ", source: file:///android_asset/www/build/main.js (1)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ADBMobile: ADBMobile Debug : Analytics - IOException while sending request, may retry(Cleartext HTTP traffic to gel.sc.omtrdc.net not permitted)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ADBMobile: ADBMobile Debug : Analytics - IOException while sending request, may retry(Cleartext HTTP traffic to gel.sc.omtrdc.net not permitted)
I/chromium: [INFO:CONSOLE(1)] "SUCCESSSSSS saveMetricByBatch ", source: file:///android_asset/www/build/main.js (1)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ADBMobile: ADBMobile Debug : Analytics - IOException while sending request, may retry(Cleartext HTTP traffic to gel.sc.omtrdc.net not permitted)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ADBMobile: ADBMobile Debug : Analytics - IOException while sending request, may retry(Cleartext HTTP traffic to gel.sc.omtrdc.net not permitted)
I/chromium: [INFO:CONSOLE(1)] "SUCCESSSSSS saveMetricByBatch ", source: file:///android_asset/www/build/main.js (1)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ADBMobile: ADBMobile Debug : Analytics - IOException while sending request, may retry(Cleartext HTTP traffic to gel.sc.omtrdc.net not permitted)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ADBMobile: ADBMobile Debug : Analytics - IOException while sending request, may retry(Cleartext HTTP traffic to gel.sc.omtrdc.net not permitted)
I/chromium: [INFO:CONSOLE(1)] "SUCCESSSSSS saveMetricByBatch ", source: file:///android_asset/www/build/main.js (1)
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'`

**Comment by lluismnd** [comment]
same error here!

When I try to logEvent native on MainActivity is working ok, but with plugin I always see that error

**Comment by chemerisuk** [comment]
Not related to this plugin.
