### ISSUE TITLE
set value of $FIREBASE_ANALYTICS_COLLECTION_ENABLED on capacitor

### ISSUE THREAD

**Issue by pantos27** [chemerisuk/cordova-plugin-firebase-analytics#149]
looks like there's an issue with setting FIREBASE_ANALYTICS_COLLECTION_ENABLED 
I'm using ionic 5, capacitor 2 on a react project

Getting this log:
`Key firebase_analytics_collection_enabled expected Boolean but value was a java.lang.String.  The default value false was returned.`

**Comment by chemerisuk** [comment]
@pantos27 better to ask ionic team, it should work.

**Comment by pantos27** [comment]
nice

**Comment by dalepo** [comment]
@pantos27 did you fix this?

**Comment by pantos27** [comment]
@dalepo I manually set the flags to true in the info.plist and AndroidManifest files

**Comment by dalepo** [comment]
For Android under `<application>`
```xml
      <meta-data
        tools:replace="android:value"
        android:name="firebase_analytics_collection_enabled"
        android:value="true"/>
```
You'll have to add `xmlns:tools="http://schemas.android.com/tools"` to your manifest tag

**Comment by SergioSuarezDev** [comment]
Same problem here, solved with **dalepo** instructions, thanks!
