### ISSUE TITLE
Build not working after installing firebase-analytics

### ISSUE THREAD

**Issue by csnv** [chemerisuk/cordova-plugin-firebase-analytics#150]
List of plugins:

> cordova-plugin-audio-recorder 1.1.0 "Cordova Audio Recorder Plugin"
> cordova-plugin-buildinfo 4.0.0 "BuildInfo"
> cordova-plugin-camera 4.1.0 "Camera"
> cordova-plugin-device 2.0.3 "Device"
> cordova-plugin-dialogs 2.0.2 "Notification"
> cordova-plugin-file 6.0.2 "File"
> cordova-plugin-file-opener2 2.2.1 "File Opener2"
> cordova-plugin-firebase-analytics 4.2.0 "FirebaseAnalyticsPlugin"
> cordova-plugin-media-capture 3.0.3 "Capture"
> cordova-plugin-network-information 2.0.2 "Network Information"
> cordova-plugin-statusbar 2.4.3 "StatusBar"
> cordova-plugin-whitelist 1.3.4 "Whitelist"
> cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
> cordova-support-google-services 1.4.0 "cordova-support-google-services"
> kapsel-plugin-authproxy 4.2.11 "AuthProxy"
> kapsel-plugin-corelibs 4.2.11 "CoreLibs"
> kapsel-plugin-i18n 4.2.11 "i18n"
> kapsel-plugin-inappbrowser 4.2.11 "InAppBrowser"
> kapsel-plugin-logger 4.2.11 "Logger"
> kapsel-plugin-logon 4.2.11 "Logon"
> kapsel-plugin-odata 4.2.11 "OData"
> kapsel-plugin-push 4.2.11 "Push"
> kapsel-plugin-settings 4.2.11 "Settings"
> kapsel-plugin-ui5 4.2.11 "ui5"
> phonegap-nfc 1.0.3 "NFC"

Error after running cordova run or cordova build after installing firebase-analytics:

> FAILURE: Build failed with an exception.> Task :app:preDebugBuild FAILED
> Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.google.firebase, artifactId=firebase-messaging, version=17.5.0), toArtifact=Artifact(groupId=com.google.firebase, artifactId=firebase-iid), toArtifactVersionString=[17.1.1])
> 
> 
> * What went wrong:
> Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> > In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[17.1.
>   1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
> 
>   Dependency failing: com.google.firebase:firebase-messaging:17.5.0 -> com.google.firebase:firebase-iid@[17.1.1], but fire
>   base-iid version was 20.0.2.
> 
>   The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
>   ifact with the issue.
>   -- Project 'app' depends onto com.google.firebase:firebase-messaging@17.5.0
>   -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.3.0
>   -- Project 'app' depends onto com.google.firebase:firebase-iid@20.0.2
>   -- Project 'app' depends onto com.google.firebase:firebase-analytics@17.3.+
>   -- Project 'app' depends onto com.google.android.gms:play-services-measurement-api@17.3.0
> 
>   For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
>   endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
>   github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
>   uild.gradle file.

**Comment by csnv** [comment]
Apparently the issue is conflicting dependencies with kapsel-plugin-push 4.2.11 "Push"
How can I fix this?

**Comment by csnv** [comment]
The issue was the plugin kapsel-plugin-push had a dependency on firebase:messaging:17.5.0, I've resolved this issue by manually setting that dependency on v 20.+.

**Comment by hanslbua** [comment]
Hello, i have the same problem after installing that plugin. any suggestions?
