### ISSUE TITLE
Log Event is not working on iOS

### ISSUE THREAD

**Issue by nichovski** [chemerisuk/cordova-plugin-firebase-analytics#151]
Hello,

It is entering in the log event and return success but the event is not sending anything to analytics. Any suggestions what can causing this issue?

Thanks

**Comment by azerturk** [comment]
Hello,
Can you please review #156 and give me some of your opinions?  I opened issue which related android version. It seems that no one active there and you also have issues like me but i thing your problem related only the events. Thanks.

**Comment by webteambel** [comment]
Same for me on iOS
```
this.firebaseAnalytics.logEvent(eveName, { page: PageName })
      .then((res: any) => console.log('analytics', res))
      .catch((error: any) => console.error(error));
```
I got always Null in console :/ I don't think this is working

**Comment by chemerisuk** [comment]
@nichovski check your Firebase configuration.

@GroupeBEL this is normal behavior.
