### ISSUE TITLE
How to log ecommerce purchases events?

### ISSUE THREAD

**Issue by maxkopych** [chemerisuk/cordova-plugin-firebase-analytics#164]
Hi, I'm new in firebase. Sorry maybe for stupid question:). But If you could provide example how to log purchase events.

I was trying to do something like this

```
cordova.plugins.firebase.analytics.logEvent("purchase", {
            'id': 'T' + Date.now(),
            'affiliation': 'TEST APP',
            'currency': 'USD',
            'value': '100.00',
            'tax': `2.0`,
            'shipping': `10.0`,
            'coupon': ""
        });
```

**Comment by chemerisuk** [comment]
I believe it should work with your call, just use numbers for numeric parameter values (tax, value, shipping etc.).
