### ISSUE TITLE
"Illformed requirement" error when trying to resolve the $IOS_FIREBASE_ANALYTICS_VERSION variable

### ISSUE THREAD

**Issue by msimkunas** [chemerisuk/cordova-plugin-firebase-analytics#165]
Building the latest iOS version of the plugin (v4.4.1) throws an "Illformed requirement" error regarding the `$IOS_FIREBASE_ANALYTICS_VERSION` variable. I'm trying to build this plugin with Ionic + Capacitor.

The `README` states:

```
Use variables ANDROID_FIREBASE_ANALYTICS_VERSION or IOS_FIREBASE_ANALYTICS_VERSION to override dependency versions for Firebase SDKs.
```

...and so I've tried adding the `IOS_FIREBASE_ANALYTICS_VERSION` key to the `Info.plist` file but this didn't resolve the issue. It seems that this variable is not replaced with the actual value during build. Is this plugin incompatible with Capacitor?

**Comment by howiesommerfeld** [comment]
I'm having the same issue when trying to run pod install in order to build the iOS version after installing the Ionic + Capacitor plugin.

**Comment by chemerisuk** [comment]
This is a cordova plug-in. Better to ask capacitor team.
