### ISSUE TITLE
Conflict with phonegap-plugin-push plugin- iOS

### ISSUE THREAD

**Issue by tom8henry** [chemerisuk/cordova-plugin-firebase-analytics#167]
Hello,

While installing then cordova-plugin-firebase-analytics plugin, I am getting conflict with phonegap-plugin-push plugin. Below is the use-case:

- If we installed firebase-analytics first then phonegap-plugin-push.
**Result** : phonegap-plugin-push failed to installed.

- If we installed phonegap-plugin-push first then firebase-analytics.
**Result :** firebase-analytics failed to installed.

**Error:**
Installing "cordova-plugin-firebase-analytics" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
pod: Command failed with exit code 1

**Here is the details:**
Cordova version : 10.0.0
iOS version : 6.1.0
cordova-plugin-firebase-analytics version: 4.4.1 
phonegap-plugin-push: 2.3.0
Pod version: 1.9.3

Could you please help me out with this?? 

Thanks in advance 🙏

**Comment by chemerisuk** [comment]
`phonegap-plugin-push` uses old firebase SDKs. You can't use the latest version of `cordova-plugin-firebase-analytics` with that plugin. Use older version:

```sh
cordova plugin add phonegap-plugin-push
cordova plugin add cordova-plugin-firebase-analytics@1.1.1
```

**Comment by tom8henry** [comment]
Thanks lot @chemerisuk for quick reply. 
the latest version of firebase-analytics@4.4.1 and version 1.1.1 is around a year old. 
Is version will compatible with latest iOS SDK and cordova platform iOS@6.1.0 ?

Please suggest.

**Comment by chemerisuk** [comment]
@tom8henry I can't recommend to use `phonegap-plugin-push` - it's archived and deprecated now. Try `cordova-plugin-firebase-messaging`, it's compatible with the latest `cordova-plugin-firebase-analytics`

**Comment by jcesarmobile** [comment]
There is a fork of the plugin in progress that will use a new package, better migrate to it https://github.com/havesource/cordova-plugin-push

**Comment by chemerisuk** [comment]
@jcesarmobile as far as I see it’s not stable yet.

**Comment by jcesarmobile** [comment]
There is no official release yet, but for people using 2.3.0 of the phonegap plugin, this one is way more up to date and the API is still the same. Is as stable as the phonegap one could be before it was abandoned.

**Comment by rdesimone** [comment]
https://github.com/havesource/cordova-plugin-push and this plugin can coexist.

in push plugin `plugin.xml` has to be modified by setting the version directly or better by `$IOS_FIREBASE_ANALYTICS_VERSION`:

`pod` version has to be the same as in this plugin.

```
<pods use-frameworks="true">
    <pod name="Firebase/Messaging" spec="~> 6.32.2" />
</pods>
```

`~> 6.32.2` works for both.
