### ISSUE TITLE
Cordova - ArgumentError - Illformed requirement `"$IOS_FIREBASE_ANALYTICS_VERSION"`

### ISSUE THREAD

**Issue by Reqven** [chemerisuk/cordova-plugin-firebase-analytics#168]
I know there has been a few other issues about the same problem with different variable names in the past, but it doesn't work for me since I updated the plugin to the latest version.

I'm using `cordova@9.0.0` and `cordova-plugin-firebase-analytics@4.4.1`.

The generated `PodFile` and `pods.json` contain the raw string "$IOS_FIREBASE_ANALYTICS_VERSION" instead of its substituted value.

```
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

target 'App' do
	project 'App.xcodeproj'
	pod 'Firebase/Analytics', '$IOS_FIREBASE_ANALYTICS_VERSION'
end
```

Running `ionic cordova platform add ios --verbose` fails with 
```
ArgumentError - Illformed requirement `"$IOS_FIREBASE_ANALYTICS_VERSION"`
...
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1
```

No issues so far when adding the `android` platform.
Any idea ? Thanks

**Comment by geeksilva97** [comment]
This error was happening to me too. I'm that is a problem to get the default version defined in **plugin.xml**. Try to install passing the variable with the version,

```ionic cordova plugin add cordova-plugin-firebase-analytics --variable IOS_FIREBASE_ANALYTICS_VERSION="~> 6.31.0"```

But I thinks that is better to remove the spec definition of plugin, @chemerisuk. So it will get automatic.

**Comment by geeksilva97** [comment]
After fix it I was getting:

```
cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:3:9: fatal error: 
      module 'Firebase' not found
@import Firebase;
 ~~~~~~~^~~~~~~~
```

So, to solve it, I forked and changed the file `FirebaseAnalyticsPlugin.m`. In addition I removed the spec from plugin.xml that solves the version problem too.

Check it out https://github.com/geeksilva97/cordova-plugin-firebase-analytics

**Comment by Reqven** [comment]
> ionic cordova plugin add cordova-plugin-firebase-analytics --variable IOS_FIREBASE_ANALYTICS_VERSION="~> 6.31.0"

```
"cordova-plugin-firebase-analytics": {
  "IOS_FIREBASE_ANALYTICS_VERSION": "~> 6.31.0"
}
```

I already tried this exact command, and even with the variable being added into the `packages.json`, still doesn't work.
The variable is still not being replaced. I have no idea why it would work fine for Android and not for iOS.

**Comment by geeksilva97** [comment]
> > ionic cordova plugin add cordova-plugin-firebase-analytics --variable IOS_FIREBASE_ANALYTICS_VERSION="~> 6.31.0"
> 
> ```
> "cordova-plugin-firebase-analytics": {
>   "IOS_FIREBASE_ANALYTICS_VERSION": "~> 6.31.0"
> }
> ```
> 
> I already tried this exact command, and even with the variable being added into the `packages.json`, still doesn't work.
> The variable is still not being replaced. I have no idea why it would work fine for Android and not for iOS.

This happened to me too. Try to clean all and exec the command again. Something like:

1. `rm -rf platforms plugins www node_modules`
2. `npm i`
3. `ionic cordova plugin add cordova-plugin-firebase-analytics --variable IOS_FIREBASE_ANALYTICS_VERSION="~> 6.31.0"`
4. `ionic cordova prepare ios`.

Alternatively you can do the changes that ai suggested early or instal from my repo using `ionic cordova plugin add https://github.com/geeksilva97/cordova-plugin-firebase-analytics`

**Comment by chemerisuk** [comment]
@Reqven @geeksilva97 upgrade your `cordova-ios` version to 6.0.0 at least.
