### ISSUE TITLE
setScreenName on iOS and setCurrentScreen on Android are deprecated

### ISSUE THREAD

**Issue by mcfarljw** [chemerisuk/cordova-plugin-firebase-analytics#170]
Android: https://firebase.google.com/docs/analytics/screenviews#java

```java
Bundle bundle = new Bundle();
bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, screenName);
mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SCREEN_VIEW, bundle);
```

iOS: https://firebase.google.com/docs/analytics/screenviews#objective-c

```objectivec
[FIRAnalytics logEventWithName:kFIREventScreenView parameters:@{kFIRParameterScreenName: screenName}]
```

**Comment by chemerisuk** [comment]
Just use logEvent.

https://github.com/chemerisuk/cordova-plugin-firebase-analytics#disable-automatic-screen-collection

**Comment by mcfarljw** [comment]
I'm not sure if it's mentioned in the docs but it's still not 100% clear to me how to switch to using `logEvent` as a replacement. Looking at the docs it looks like the event constant `FirebaseAnalytics.Event.SCREEN_VIEW` maps to `screen_view` and the bundle parameter `FirebaseAnalytics.Param.SCREEN_NAME` maps to `screen_name` so something like below would work?

```js
cordova.plugins.firebase.analytics.logEvent('screen_view', { screen_name: 'screen-1' })
```

https://firebase.google.com/docs/analytics/screenviews#manually_track_screens

I think it'd be better to have a convenience method for handling manual screen tracking rather than relying on `logEvent` for a cleaner look and better usage of the native constant values.

**Comment by chemerisuk** [comment]
@mcfarljw you are right - just use string constant values in your `logEvent` call:

```js
```

**Comment by chemerisuk** [comment]
@mcfarljw I've decided to undeprecate `setCurrentScreen` and [reimplement](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/commit/2b30cdb7d08ec9e1aeebbc0dd8fd7f4580c506d9) it with `logEvent` + constants. In future other common methods could be added to simplify usage.
