### ISSUE TITLE
cordova-support-google-services is deprecated

### ISSUE THREAD

**Issue by Pitouli** [chemerisuk/cordova-plugin-firebase-analytics#171]
It seems cordova-plugin-firebase-analytics is not working anymore on my app, and I believe it could be related to the deprecation of https://github.com/chemerisuk/cordova-support-google-services/blob/master/README.md and the update to cordova android 9: https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html

If I keep the support google services plugin, I have error because of the GradlePluginGoogleServicesEnabled.
If I remove it, I have alert that the firebase-analytics plugin is depending on it.

Do you think an update of this plugin would be possible?

At the moment, I am having a hard time simply RUNNING cordova correctly, so I sadly do not have the experience yet to do a PR myself :(

**Comment by chemerisuk** [comment]
@Pitouli you should not have an issue with `GradlePluginGoogleServicesEnabled`. Just reinstall all plugins that rely on `cordova-support-google-services`. During the installation step `cordova-support-google-services` is ignored by the cordova-cli.

**Comment by Pitouli** [comment]
You're completely right! Sorry to have bothered you for nothing
