### ISSUE TITLE
Failed to install plugin cordova-support-google-services

### ISSUE THREAD

**Issue by mrbhaskar** [chemerisuk/cordova-plugin-firebase-analytics#172]
@chemerisuk 
Installing "cordova-support-google-services" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0

**Comment by chemerisuk** [comment]
This is expected behavior.

**Comment by sebastianovide** [comment]
Hi. by "This is expected behavior." do you mean that it will not work or that we can just ignore the error?  thanks

**Comment by chemerisuk** [comment]
@sebastianovide you can just ignore this message.

**Comment by nagthgr8** [comment]
The info message could have been a little informative than ..does not support if the plugin is a built in feature
