### ISSUE TITLE
Dependency cordova-support-google-services does not support cordova-android 9.0.0

### ISSUE THREAD

**Issue by ucsbricks** [chemerisuk/cordova-plugin-firebase-analytics#173]
I failed to install this plugin, as its dependecy cordova-support-google-services got deprecated and does not support cordova-android 9.0.0
> DEPRECATION NOTICE: no longer needed. Use preference GradlePluginGoogleServicesEnabled for cordova-android version 9 or higher.

Could you please update your plugin to work with the most recent version of cordova-android?

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/172

**Comment by fttx** [comment]
Sorry, do you plan to update it, or there is some other solution to have analytics working with cordova 9?

Thank you
