### ISSUE TITLE
Error in IOS Build

### ISSUE THREAD

**Issue by marcosjara** [chemerisuk/cordova-plugin-firebase-analytics#175]
Hello

I am having compilation problems on IOS from the cocoapods ...

Based on that..?

Where do I find relevant information about the value for these variables?

ANDROID_FIREBASE_ANALYTICS_VERSION

IOS_FIREBASE_ANALYTICS_VERSION

**Comment by chemerisuk** [comment]
https://stackoverflow.com/questions/25553724/add-a-plugin-with-variables
