### ISSUE TITLE
Incompatibility with newest cordova 10, cordova-android-9 and, support-google-services

### ISSUE THREAD

**Issue by Vulisha** [chemerisuk/cordova-plugin-firebase-analytics#176]
I have updated my Cordova to 10.0.0 and Cordova-android to 9.0.0 and all the plugins to newest versions. 

Now it won't build successfully since I get error - 
```
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android
```
That plugin git says
`DEPRECATION NOTICE: no longer needed. Use preference GradlePluginGoogleServicesEnabled for cordova-android version 9 or higher.`
But when I try to remove it it is said it is needed for cordova-plugin-firebase-analytics. Sort of infinity loop :)
It is working on Mac properly.

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/172
