### ISSUE TITLE
Conflict with phonegap-plugin-push

### ISSUE THREAD

**Issue by abdfork** [chemerisuk/cordova-plugin-firebase-analytics#18]
Please, has anyone managed to use this together with phonegap-plugin-push?

Using both plugins on android seems fine but I get an error about duplication of definitions when building for ios.

I know about cordova-plugin-firebase-messaging, but I don't want to rewrite all that code at the moment.

**Comment by FdezRomero** [comment]
I'm using both plugins in production without problems. If you can be more specific about the problem (or paste the error) maybe someone will be able help you ;-)

**Comment by abdfork** [comment]
Thank you for your quick response!
I should have pasted the error indeed, but I though it was a long shot, it seems I was wrong again.

When I run `ionic run ios`
I get

```
The following build commands failed:

duplicate symbol _OBJC_CLASS_$_GSDK_PBMessageSignatureProtocol in:
    /Users/alex/src/scotch-box/public/tshaped/frontend/platforms/ios/Pods/GoogleInterchangeUtilities/Frameworks/frameworks/GoogleInterchangeUtilities.framework/GoogleInterchangeUtilities(PBUtilities.o)
    /Users/alex/src/scotch-box/public/tshaped/frontend/platforms/ios/T-shaped/Plugins/phonegap-plugin-push/GCM/Libraries/libProtocolBuffers.a(PBUtilities.o)
ld: 343 duplicate symbols for architecture x86_64

	Ld build/emulator/MyApp.app/MyApp normal x86_64
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/alex/src/scotch-box/public/myapp/frontend/platforms/ios/cordova/build-debug.xcconfig,-workspace,MyApp.xcworkspace,-scheme,MyApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 5s,build,CONFIGURATION_BUILD_DIR=/Users/alex/src/scotch-box/public/myapp/frontend/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/alex/src/scotch-box/public/myapp/frontend/platforms/ios/build/sharedpch`

```

The full output here: http://pastebin.com/g9awAZDy

**Comment by abdfork** [comment]
Could you please tell me which versions are you running in your app?

**Comment by abdfork** [comment]
It seems I fixed it somehow, but I'm not sure what really the problem was.

If anybody gets here, see:
https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/10
