### ISSUE TITLE
Plugin doesn't support this project's cordova-android version

### ISSUE THREAD

**Issue by SatyapriyaAtDure** [chemerisuk/cordova-plugin-firebase-analytics#181]
My cordova version is 9.0.0 but still i am getting below error.

Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement: <9.0.0
Skipping 'cordova-support-google-services' for android

**Comment by chemerisuk** [comment]
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/172
