### ISSUE TITLE
Google Play Console: We found ads in your app

### ISSUE THREAD

**Issue by geshub** [chemerisuk/cordova-plugin-firebase-analytics#183]
I've got a warning in my google play console saying my app is using ad SDKs (App content).
Looking through all the dependencies in my app, I think it may be coming from com.google.android.gms:play-services-ads-identifier:17.0.0 that is added by com.google.firebase:firebase-analytics:18.0.
Is it necessary for cordova-plugin-firebase-analytics to work correctly ?
If it's not, is it possible to remove the dependency as indicated here: https://stackoverflow.com/a/64798971/12281292 ?

Thanks for your help,

<img width="992" alt="Screenshot 2021-01-11 at 10 26 59" src="https://user-images.githubusercontent.com/4352726/104169521-9cf10200-53f7-11eb-837c-0e98cd5b09ee.png">

**Comment by geshub** [comment]
Hi, nobody got that issue ?

**Comment by canadaka** [comment]
I would also like this removed. It seems it could be done in the Android build.gradle using something like
```
implementation ('com.google.firebase:firebase-analytics') {
    exclude module: "play-services-ads-identifier"
}
```

But not sure how to do that from this plugin and in the Cordova world.

**Comment by mozhn** [comment]
This problem still persists. Why was it closed?
