### ISSUE TITLE
New to Cordova Firebase Analytics

### ISSUE THREAD

**Issue by ElwyneMabanglo** [chemerisuk/cordova-plugin-firebase-analytics#19]
Hi, 

Thank you for your time to read my issue.

I am having some issue trying to get the analytics working. 

I've placed the function "window.FirebasePlugin.logEvent("page_view", {page: "dashboard"});" within my onDeviceReady() function to test it out, but unable to see any results on firebase dashboard.

Please advice, thanks very much.

**Comment by abdfork** [comment]
How long did you wait? It will take 24h for the log to appear on firebase dashboard.
You can only read within the same day if you link it to bigquery.

**Comment by mcfarljw** [comment]
It will take about 24h for it to show up on the dashboard. You can however check logcat to verify that the events are actually sending. Scroll down to the `View events in the Android Studio debug log` section in the following link:

https://firebase.google.com/docs/analytics/android/events
