### ISSUE TITLE
unable to add firebase-analytics plugin for iOS platform 

### ISSUE THREAD

**Issue by sarathi0333** [chemerisuk/cordova-plugin-firebase-analytics#190]
i tried to add `firebase-analytics` plugin into my ionic project, the process exited with exit code 1. I debugged the issue by running `pod install --verbose` inside `platforms/ios`, I am getting the below error.

`CocoaPods could not find compatible version for "nanopb"`
 `    In Snapshot (podfile.lock) :`
 `      nanopb ( =2.30908.0, ~>2.3.908)`

Hope this is not the actual issue.
As I already have **cordova-plugin-fcm-with-dependecy-updated**, this plugin uses `nanopb ` version `2.30908.0`, when i tried to install **cordova-plugin-firebase-analytics** it still uses the `nanopb ` version `2.30906.0` i guess that's the reason for the above error.

I did a work around, I deleted the _podfile.lock_ and tried `pod install`. now it works. But I cannot do this as I have pipeline setup.

**Comment by YaroslavG** [comment]
@sarathi0333 
Hi,
 I have the same issues with pipeline, do you find a solution ?
