### ISSUE TITLE
[Action Required] Update your Firebase Performance Monitoring SDKs before January 10, 2022

### ISSUE THREAD

**Issue by pendelru** [chemerisuk/cordova-plugin-firebase-analytics#192]
We received a notification from the Firebase team telling us to update our SDKs. In our ionic5 app we're using the "cordova-plugin-firebase-analytics 5.0.0" plugin. 
Is an update of this plugin / repo planned regarding this issue? Thanks for your help.

E-Mail notification from Firebase:

We’ve identified you’re using an older version of the Firebase Performance Monitoring SDKs (Android: 16.2.1 and older, and iOS: 2.1.2 and older). Although they'll continue to run as configured, older SDKs will no longer capture new performance metrics after January 10, 2022. Performance metrics that were logged prior to January 10, 2022 will be available for 90 days until April 10, 2022.

What do I need to know?
We've continued to improve Firebase Performance Monitoring. This means, newer clients use open source SDKs that include real time metrics and provide detailed performance insight into how your sessions are performing. Newer versions will continue to log the metrics you have always been tracking with the addition of these new performance monitoring capabilities.

What do I need to do?
Update your Firebase Performance Monitoring SDKs before January 10, 2022 as follows:

Review the release notes for Android or iOS, based on your deployment.
Update the version of Firebase Performance in your application to 16.2.2 (or newer) on Android and 2.2.0 (or newer) on iOS.
What if I don’t do anything?
After January 10, 2022, applications using older versions of the SDKs will not display any new performance metrics on the performance monitoring console. Also, your performance metrics logged prior to January 10, 2022 will be available for 90 days, after which, the console will not display any data.

If you have questions, please reach out to Firebase Support.

Thanks,
Visu on behalf of the Firebase team

**Comment by chemerisuk** [comment]
This repo doesn't contain any reference to Firebase Performance Monitoring SDKs.
