### ISSUE TITLE
Disable automatic collection of events

### ISSUE THREAD

**Issue by franalt** [chemerisuk/cordova-plugin-firebase-analytics#196]
Hello everyone,

I was wondering if there was a way to `disable automatic collection of events` like we can `disable automatic collection of screen views`.

I'm having an issue with subscriptions conversions being collected every time the app is opened. The event `app_store_subscription_renew` gets called and looses true value.

Is there a way to turn off automatic event collection? Or a way to control this particular event?

Cheers!

**Comment by franalt** [comment]
Would this still allow mually sent analytics through?

**Comment by chemerisuk** [comment]
@franalt yes, manual events are still allowed

**Comment by chemerisuk** [comment]
@franalt nope, after double checking I realised that this setting disables all analytics data collection
