### ISSUE TITLE
Need support for e-commerce items (i.e. products) for Firebase Analytics

### ISSUE THREAD

**Issue by himadridev** [chemerisuk/cordova-plugin-firebase-analytics#198]
Firebase Analytics supports [Measure Ecommerce](https://firebase.google.com/docs/analytics/measure-ecommerce),

Which allows measurement of user interactions with products across your users' shopping experiences, including interactions such as product (item) list views, product list clicks, viewing product details, adding a product to a shopping cart, initiating the checkout process, purchases, and refunds.

**Problem Statement:**
In Android, we are parsing the params & only allowing String, Integer, Double, Long but not Array for the items (i.e. products).

**Solution**
we need to allow a JSONArray, which sends the items (i.e. products) along with e-commerce event params.

**Comment by himadridev** [comment]
#197 Raised a pull request, Please review.

**Comment by chemerisuk** [comment]
Support added in v7.0.4
