### ISSUE TITLE
Plugin doesn't support this project's cordova version

### ISSUE THREAD

**Issue by TildeGv9** [chemerisuk/cordova-plugin-firebase-analytics#199]
Hello, I'm trying to build my iOS app but I got this error message:

Installing "cordova-plugin-firebase-analytics" for ios
Plugin doesn't support this project's cordova version. cordova: 9.0.1, failed version requirement: >=10.0.0

I already have:
cordova -v 10.0.0 (cordova-lib@10.1.0)
cordova-android -> 9.1.0
cordova-ios -> 6.1.0

--- npm outdated                             
Package            Current  Wanted  Latest  Location
cordova             10.0.0  10.0.0  11.0.0  Fenix

Can anyone help me?

**Comment by TildeGv9** [comment]
@chemerisuk @jonas-m- @FdezRomero @robertodias180 Can you help me on this topic, pls?

**Comment by TildeGv9** [comment]
I get same error message if I downgrade to project's cordova-version to 8.12 and 11.0.0

**Comment by TildeGv9** [comment]
@chemerisuk Why did you close the issue?

**Comment by manongwang** [comment]
Hi,
I have the same issues with pipeline, do you find a solution ?
