### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by 78lab** [chemerisuk/cordova-plugin-firebase-analytics#2]
I got this error

/platforms/android/src/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:89: error: illegal start of expression

        this.firebaseAnalytics.setAnalyticsCollectionEnabled(enabled === "true");
                                                                       ^

1 error

and this one too

/ionic/my132/platforms/android/src/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:98: error: <identifier> expected

    private void setCurrentScreen(callbackContext, String name) {

                                                 ^

1 error

**Comment by robertodias180** [comment]
@78lab #3 should fix it. Give it a try

**Comment by chemerisuk** [comment]
@78lab the first error fixed in #1 - try version from the master branch now
