### ISSUE TITLE
install plugin with error

### ISSUE THREAD

**Issue by sonicwong** [chemerisuk/cordova-plugin-firebase-analytics#20]
Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.11 
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.2.1 Build version 8C1002

when I install the plugin, 404 error for download: node-v48-darwin-x64.tar.gz

======

$ cordova plugin add cordova-plugin-firebase-analytics@0.9.1
Fetching plugin "cordova-plugin-firebase-analytics@0.9.1" via npm
Installing "cordova-plugin-firebase-analytics" for android
Fetching plugin "cordova-plugin-firebase-hooks" via npm
Installing "cordova-plugin-firebase-hooks" for android
Fetching plugin "cordova-plugin-cocoapod-support" via npm
Installing "cordova-plugin-cocoapod-support" for android
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.9.4 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz 
In file included from ../vendor/libxml/xpath.c:476:
../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
trio_is_negative
^
2 warnings generated.
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
ANDROID_HOME=/Users/sonic/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
Subproject Path: CordovaLib
Incremental java compilation is an incubating feature.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL

Total time: 1.558 secs
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Installing "cordova-plugin-firebase-analytics" for ios
Installing "cordova-plugin-firebase-hooks" for ios
Installing "cordova-plugin-cocoapod-support" for ios

**Comment by chemerisuk** [comment]
Try to update your nodejs to version 4 at least.
