### ISSUE TITLE
Library expects a BoM package: com.google.firebase:firebase-analytics

### ISSUE THREAD

**Issue by geshub** [chemerisuk/cordova-plugin-firebase-analytics#205]
When installing the plugin or building on Android, i see "Library expects a BoM package: com.google.firebase:firebase-analytics" in the logs. 
I tried to install the plugin with --variable ANDROID_FIREBASE_BOM_VERSION="30.3.1" but it keeps asking for a BoM package. 
Plugin seems to be working correctly, just wanted to see if it can cause any trouble ?
Thank you

**Comment by sestienne** [comment]
Hi, 

I've got the same problem but I'm unable to build. 
Regarding recent changes on file plugin.xml I find that commit "Add required use-frameworks="true", add ANDROID_FIREBASE_BOM_VERSION" doesn't seem to work in my case. 

Roll back for android part work fine for me (even if actual code seems ok regarding this doc : https://firebase.google.com/docs/android/learn-more) :

Replace
<preference name="ANDROID_FIREBASE_BOM_VERSION" default="30.3.1" />
By
<preference name="ANDROID_FIREBASE_ANALYTICS_VERSION" default="21.1.1" />

And replace 
<framework src="platform('com.google.firebase:firebase-bom:$ANDROID_FIREBASE_BOM_VERSION')" />
<framework src="com.google.firebase:firebase-analytics" />
By 
<framework src="com.google.firebase:firebase-analytics:$ANDROID_FIREBASE_ANALYTICS_VERSION" />

@chemerisuk Is it possible for you to check why we have this error ?

**Comment by tzappia** [comment]
It doesn't seem like this should be an issue, it's just a warn log that was added when support for BOM was added. In the Cordova Android tool code, you'll see:
```
if (/:.*:/.exec(p)) {
  mavenRef = p;
} else if (/:.*/.exec(p)) {
  // Support BoM imports
  mavenRef = p;
  events.emit('warn', 'Library expects a BoM package: ' + p);
} else {
  ...
```
I think you can safely ignore this message. Any build errors you have are not likely a result of seeing this.

**Comment by EMI-INDO** [comment]
**it works for me**

cordova platform rm android

`cordova plugin rm cordova-plugin-firebase-analytics`
`cordova plugin rm cordova-support-android-plugin`

**Add config.xml**
```
<preference name="GradlePluginGoogleServicesEnabled" value="true" />
<preference name="GradlePluginGoogleServicesVersion" value="4.3.8" />
<preference name="ANDROID_FIREBASE_ANALYTICS_VERSION" default="19.0.+" />
```


`cordova plugin add cordova-plugin-firebase-analytics@6.1.0`


cordova platform add android@11.0.0

cordova build android

**Comment by chemerisuk** [comment]
It’s just an information message from Cordova scripts.
