### ISSUE TITLE
Android - Data do not send to firebase analytics

### ISSUE THREAD

**Issue by Jasphine** [chemerisuk/cordova-plugin-firebase-analytics#208]
Hi,

I have installed this plugin in Android and using the logEvent to log the screen-views , like this :
cordova.plugins.firebase.analytics.logEvent('screen_view', {
			  screen_name: 'Home-Page', 
			  screen_class: 'MainActivity'
			});

However, the data did not send to firebase analytics until if I uninstalled the app, then the data only send to firebase analytics and appear on firebase analytics.

May I know how to log the real-times data to firebase analytics as long as user interact with the app?

Appreciate your help. Thanks

**Comment by Jasphine** [comment]
Hi,

I tried to use 'setCurrentScreen' , but have the same issues as well.

**Comment by Ericsig** [comment]
Same issue. The events don't arrive to Analytics until I uninstall the app.

**Comment by EMI-INDO** [comment]
**it works for me**

cordova platform rm android

`cordova plugin rm cordova-plugin-firebase-analytics`
`cordova plugin rm cordova-support-android-plugin`

**Add config.xml**
<preference name="GradlePluginGoogleServicesEnabled" value="true" />
<preference name="GradlePluginGoogleServicesVersion" value="4.3.8" />
<preference name="ANDROID_FIREBASE_ANALYTICS_VERSION" default="19.0.+" />


`cordova plugin add cordova-plugin-firebase-analytics@6.1.0`


cordova platform add android@11.0.0

cordova build android

**Comment by stevesum** [comment]
Same here. screen_view, session_starts, and other default events are sent in real-time monitoring, but not events sent by logEvent function.

**Comment by st9450602** [comment]
same too, anybody have solution for this issue?

**Comment by EMI-INDO** [comment]
@chemerisuk 

I have tested,

Works fine on IOS. 
Doesn't work on Android. data not sent to firebase analytics.
