### ISSUE TITLE
'FirebaseAnalytics' not found -  IOS build

### ISSUE THREAD

**Issue by lucav90** [chemerisuk/cordova-plugin-firebase-analytics#21]
i have this error after build.

**Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:2:9: Module 'FirebaseAnalytics' not found**

on android works. what is the problem with ios?

**Comment by lucav90** [comment]
no solution?

**Comment by warrenkeith** [comment]
Getting the same myself :s

**Comment by C1PR14N055** [comment]
+1

**Comment by epetre** [comment]
It seems to still be happening exactly as described, was this claused because it's already being worked on or it's something you don't plan on fixing?

**Comment by epetre** [comment]
seems to be caused by 
```
<pod id="Firebase/Analytics" />
```
in
```
plugins/cordova-plugin-firebase-analytics/plugin.xml
```

changing it to 
```
<pod id="Firebase/Core" />
```
Makes it compile...

**Comment by Igfig** [comment]
I'm getting the same issue... the workaround isn't helping in my case, though.

**Comment by epetre** [comment]
I wasn't getting any feed on the debug console either... I'm not sure if this plugin is still maintained to be honest. It's really hard just to set it up properly.

**Comment by Igfig** [comment]
Actually, I think I figured out what was going on. It's a conflict with phonegap-plugin-push (for me at least), which still uses GCM instead of Firebase. When you install one of the plugins, it'll write its own dependencies to the podfile, and remove the other one's.

My solution was to move to the 2.0 branch of phonegap-plugin-push. It has some issues of its own, but they're unrelated to this one.

**Comment by kodeine** [comment]
i am getting the same error, what fixed it guys?

**Comment by Igfig** [comment]
Ultimately, switching to [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase).

**Comment by epetre** [comment]
Yeah I don't know why this plugin is shown under https://ionicframework.com/docs/native, it's the only plugin that never worked for me no matter what I tried and I tried it a couple of times in the past year.

**Comment by Thomasbehan** [comment]
To fix this you have to go to the platforms/ios directory and run in the terminal:

`sudo gem install cocoapods`

Then run

`pod install`

This should then add the missing modules 
This will potentially work for #61 #21 #41

**Comment by goodok21** [comment]
@Thomasbehan I've been installed pods in `ios` directory, but still have this error

**Comment by thanhphamtien1** [comment]
I still have this issue, how to fix it ..., i've tried every above solutions ...

**Comment by shamsundhar** [comment]
i am getting this issue, how to fix it?

**Comment by airflash** [comment]
have the same shit ((

**Comment by Thomasbehan** [comment]
At this stage Cordova is fairly outdated I'd suggest using react native or something more modern like that, Cordova in general can be quite buggy.
