### ISSUE TITLE
cordova-plugin-firebase-analytics version 7.0.5 is not working for android platform

### ISSUE THREAD

**Issue by balajitoverto** [chemerisuk/cordova-plugin-firebase-analytics#210]
**cordova-plugin-firebase-analytics version 7.0.5 is not supporting to run for android platform it support only IOS platform** 
![build error](https://user-images.githubusercontent.com/127953007/225317195-7ba37a03-3f40-4a53-bcfe-8b56daabd414.png)
[Error text.txt](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/files/10979978/Error.text.txt)
![Package json file image](https://user-images.githubusercontent.com/127953007/225315695-7f46975e-95d6-402c-8971-d3a05e1665f8.png)

**Comment by Alex0x47** [comment]
I'm facing the same issue, did you find any solution @balajitoverto?

**Comment by chemerisuk** [comment]
Upgrade your Cordova-android dependency.
