### ISSUE TITLE
build ios failed  - library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by lucav90** [chemerisuk/cordova-plugin-firebase-analytics#22]
i have this error on IOS when i build my app after firebase plugin installation.

ld: warning: directory not found for option '-FApp/Plugins/cordova-plugin-firebase'
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How can i solve?

regards,

**Comment by chemerisuk** [comment]
Try to run `cordova build ios` again.

**Comment by lucav90** [comment]
same problem

**Comment by hankphone** [comment]
@lucav90 @chemerisuk Not sure if this will apply to your project but this was solved for me in Ionic2 by closing Xcode and then using the .xcworkspace file instead of xcodeproj file. So, just double click the <app-name>.xcworkspace file in your project and build for your device from that.

**Comment by lucav90** [comment]
Hi,

the same problem. please tell me a solution

**Comment by tiagocedrim** [comment]
@lucav90 You can solve this issue? Same problem here.

**Comment by groupmwt** [comment]
> Hi,
> 
> I have still this issue with `cordova-plugin-firebase-analytics` on my local machine and in Ionic Pro creating a package.
> 
> That's the error from building a package in Ionic Pro for iOS and running `ionic cordova run ios --device --release` on my local machine:
> 
> ```
> ❌  ld: library not found for -lGoogleToolboxForMac
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> Here ara my local setup of Ionic:
> 
> ```
> cli packages: (/usr/local/lib/node_modules)
>     @ionic/cli-utils  : 1.19.2
>     ionic (Ionic CLI) : 3.20.0
> System:
>     Node : v9.3.0
>     npm  : 5.6.0
>     OS   : macOS Sierra
> Misc:
>     backend : pro
> ```
> Locally, I can build the package multiple times and eventually it will work. But that's not possible in Ionic Pro.
> Do you have any suggestions to solve this problem?

I am facing same issue when try to work on firebase-analytics for my ionic app, the build is getting failed and giving following error : 

> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         Ld build/emulator/iDriver.app/iDriver normal x86_64
> (1 failure)
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/dev-1/Desktop/Mukesh/IONIC_V1/iDriver/Backup/30 Oct 2018/IDriver/platforms/ios/cordova/build-debug.xcconfig,-workspace,iDriver.xcworkspace,-scheme,iDriver,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/dev-1/Desktop/Mukesh/IONIC_V1/iDriver/Backup/30 Oct 2018/IDriver/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/dev-1/Desktop/Mukesh/IONIC_V1/iDriver/Backup/30 Oct 2018/IDriver/platforms/ios/build/sharedpch
> 
> [ERROR] An error occurred while running cordova build ios (exit code 1).
>
