### ISSUE TITLE
Google Analytics warning about version of iOS SDK

### ISSUE THREAD

**Issue by mg** [chemerisuk/cordova-plugin-firebase-analytics#222]
Hi

We are getting this warning from Google

<img width="1547" alt="image" src="https://github.com/chemerisuk/cordova-plugin-firebase-analytics/assets/1972/5f53bea0-3c73-4809-8646-24fa966ee4cc">

Are there any plans to update the iOS SDK version dependency in the near future?

cheers
mg

**Comment by chemerisuk** [comment]
Have you tried to use variable IOS_FIREBASE_POD_VERSION to override pod version to the latest? More details here https://github.com/chemerisuk/cordova-plugin-firebase-analytics?tab=readme-ov-file#installation

**Comment by mg** [comment]
We have not. I did not notice that option. We will try and report back. Thanks.

**Comment by johann9898** [comment]
We tried to change IOS_FIREBASE_POD_VERSION version and it only works to build the app to the iOS up until v10.18.0. Build failed when we tried to change the version from v10.19.0 to the latest.

**Comment by KrystinaH** [comment]
Hi @chemerisuk and thanks for your plugin :)
I have this warning too in Firebase and GA4, and I have tried to update to the version that they suggest which is 10.24.0 in my package.json in the cordova plugins section like so:

```
"cordova-plugin-firebase-analytics": {
  "AUTOMATIC_SCREEN_REPORTING_ENABLED": "false",
  "ANALYTICS_COLLECTION_ENABLED": "true",
  "IOS_FIREBASE_POD_VERSION": "10.24.0"
},
```

But I always get an error while preparing my app: `Failed to install 'cordova-plugin-firebase-analytics': Error: Command failed with exit code 31`. Is it possible that the plugin does not support latest pod version and is stucked to 9.3.0?

Thanks for your help!

**Comment by chemerisuk** [comment]
@KrystinaH follow instructions from https://github.com/chemerisuk/cordova-plugin-firebase-analytics?tab=readme-ov-file#installation. Your approach to specify versions won't work
