### ISSUE TITLE
Error ios run - Could not find a valid GoogleService-Info.plist in your project

### ISSUE THREAD

**Issue by lucasound** [chemerisuk/cordova-plugin-firebase-analytics#23]
Hi,

when i try to run the ios app i have this error:

could not find a valid GoogleService-Info.plist in your project

The GoogleService-Info.plist is valid and present in cordova root ios app and into www folder.

What is the error?

**Comment by leyvicaz** [comment]
Hi @lucasound ,

Move file
project
  www/
 GoogleService-Info.plist
