### ISSUE TITLE
consider merging efforts with cordova-plugin-firebase

### ISSUE THREAD

**Issue by v3ss0n** [chemerisuk/cordova-plugin-firebase-analytics#25]
Since both have analytics and for avoiding reinventing the wheel .
https://github.com/arnesson/cordova-plugin-firebase/commits/master

**Comment by FdezRomero** [comment]
@v3ss0n The main problem with `cordova-plugin-firebase` is that it requires developers to drop `phonegap-plugin-push` and use this plugin instead, as it also handles notifications. This plugin only handles Firebase Analytics, and therefore works with the more advanced PhoneGap Push plugin.

**Comment by chemerisuk** [comment]
I think this thread can be closed, as those projects have different goals and therefore use different approaches.

**Comment by fcamblor** [comment]
@chemerisuk I guess this would be helpful to explicitely talk about differences between those 2 plugins in the README, as this is the first question that came to my head when I found `cordova-plugin-firebase` and `cordova-plugin-firebase-analytics` in the available cordova plugins

**Comment by hvaughan3** [comment]
@fcamblor The primary difference for me is that you cannot disable push notification integration when installing `cordova-plugin-firebase`. So if you use a different plugin for push notifications, you will most likely run into issue when also trying to install `cordova-plugin-firebase`.

I wish they would use a similar model to the cordova diagnostics plugin (not sure if its possible to do) and allow you to specify modules to load or not load at install time.
