### ISSUE TITLE
Error: Cannot find module '../../node_modules/xcode'

### ISSUE THREAD

**Issue by epetre** [chemerisuk/cordova-plugin-firebase-analytics#26]
After fresh install of version ~ 0.9.4 a build triggers this error...
It seems to be related to [this](https://github.com/chemerisuk/cordova-plugin-firebase-hooks/issues/1) other project, but I'm not sure yet what to do with it.

It only happens when building.

**Comment by epetre** [comment]
Closing, it seems to be a duplicate of [https://github.com/blakgeek/cordova-plugin-cocoapods-support/issues/30](#30)

**Comment by epetre** [comment]
changing
```
      xcode = context.requireCordovaModule('cordova-lib/node_modules/xcode'),
      plist = context.requireCordovaModule('cordova-lib/node_modules/plist');
```
to
```
     xcode = context.requireCordovaModule('xcode'),
      plist = context.requireCordovaModule('plist');
```

Fixes the issue for me, but then I get: 
```
Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:2:9: fatal error: module 'FirebaseAnalytics' not found
@import FirebaseAnalytics;
```
This was mentioned [here](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/21) but then closed.

**Comment by xXcoronaXx** [comment]
Same build error IOS:

Error: Cannot find module '../../node_modules/xcode'

**Comment by MarinoRaul** [comment]
Can you resolve this issue???

Same build error IOS:

Error: Cannot find module '../../node_modules/xcode'

**Comment by shirkan** [comment]
Same problem here.

**Comment by Alb93** [comment]
Same here. @chemerisuk please fix. My try was to change 
` xcode = context.requireCordovaModule('cordova-lib/node_modules/xcode'),
     plist = context.requireCordovaModule('cordova-lib/node_modules/plist');`
 to
 `xcode = require('xcode'),
      plist = require('plist');`
 but receiving som build compilation errors.

**Comment by chemerisuk** [comment]
Try version 0.10 from npm. Make sure you've read README to setup plugin correctly (there were some changes).

**Comment by merbin2012** [comment]
Nothing specified there.

**Comment by ManoloCap** [comment]
Same problem here in 2018
