### ISSUE TITLE
Build error ios - Apple Mach-O Linker (ld) Error 

### ISSUE THREAD

**Issue by lucasound** [chemerisuk/cordova-plugin-firebase-analytics#27]
Hi,

with ios version and xcode, i have this error on build.

Apple Mach-O Linker (ld) Error 

"_OBJC_CLASS_$_FIRAnalyticsConfiguration", referenced from:

"_OBJC_CLASS_$_FIRAnalytics", referenced from:

"_OBJC_CLASS_$_FIRApp", referenced from:

linker command failed with exit code 1 (use -v to see invocation)

what is the problem?

**Comment by vgnrgithub** [comment]
PushPlugin uses Cocoa Pods now, once it is installed you can not run your regular yourProjectName.xcodeproj file you must open a new file that was creating after you installed PushPlugin called yourProjectName.xcworkspace.

**Comment by oddcb** [comment]
Hello. So I got this same error myself even after opening the workspace. 

What solved it was going to `Build Settings` choose my app under `Targets` the left pane. Then find (or search for) `Other Linker Flags`, double click its value and add `$(inherited)` on a new line. After that I got it building. 

**Before adding `$(inherited)`**

![skjermbilde 2017-06-30 kl 10 37 57](https://user-images.githubusercontent.com/374889/27727813-5b2e7a94-5d80-11e7-9160-cac4c6aec73e.png)

**Adding `$(inherited)`:**

![skjermbilde 2017-06-30 kl 10 38 07](https://user-images.githubusercontent.com/374889/27727812-5b2c6d58-5d80-11e7-9432-a3bd46fb0db0.png)

**After:**

![skjermbilde 2017-06-30 kl 10 38 17](https://user-images.githubusercontent.com/374889/27727814-5b2eb0ea-5d80-11e7-9c54-8ed19cc0a5ba.png)
