### ISSUE TITLE
ionic package build error

### ISSUE THREAD

**Issue by MarinoRaul** [chemerisuk/cordova-plugin-firebase-analytics#30]
Searching for new pods
Checking com.dbaq.cordova.contactsPhoneNumbers for pods.
Checking cordova-plugin-app-event for pods.
Checking cordova-plugin-badge for pods.
Checking cordova-plugin-camera for pods.
Checking cordova-plugin-compat for pods.
Checking cordova-plugin-console for pods.
Checking cordova-plugin-contacts for pods.
Checking cordova-plugin-datepicker for pods.
Checking cordova-plugin-device for pods.
Checking cordova-plugin-file for pods.
Checking cordova-plugin-file-transfer for pods.
Checking cordova-plugin-firebase-analytics for pods.
cordova-plugin-firebase-analytics requires pod: Firebase/Analytics
Checking cordova-plugin-firebase-hooks for pods.
Checking cordova-plugin-google-analytics for pods.
Checking cordova-plugin-inappbrowser for pods.
Checking cordova-plugin-splashscreen for pods.
Checking cordova-plugin-statusbar for pods.
Checking cordova-plugin-whitelist for pods.
Checking cordova-plugin-x-socialsharing for pods.
Checking es6-promise-plugin for pods.
Checking ionic-plugin-deploy for pods.
Checking ionic-plugin-keyboard for pods.
Checking phonegap-plugin-push for pods.
Checking config.xml for pods.
Installing pods
Sit back and relax this could take a while.
    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m

Analyzing dependencies
[31mRemoving GGLInstanceID[0m
[31mRemoving GoogleCloudMessaging[0m
[31mRemoving GoogleIPhoneUtilities[0m
[31mRemoving GoogleInterchangeUtilities[0m
[31mRemoving GoogleSymbolUtilities[0m
[31mRemoving GoogleUtilities[0m
Downloading dependencies
[32mInstalling Firebase (4.0.2)[0m
[32mInstalling FirebaseAnalytics (4.0.1)[0m
[32mInstalling FirebaseCore (4.0.2)[0m
[32mInstalling FirebaseInstanceID (2.0.0)[0m
[32mInstalling GoogleToolboxForMac (2.1.1)[0m
Generating Pods project

Integrating client project

Sending stats

[32mPod installation complete! There is 1 dependency from the Podfile and 5 total pods installed.[0m

Updating ios build to use workspace.
Adding schemes
Error: Cannot find module '../../node_modules/xcode'

**Comment by Alb93** [comment]
I think that the problem is quite similar to #10.
Not solved but it is better if we keep the same problem on only one post.

**Comment by chemerisuk** [comment]
Try version 0.10 from npm. Make sure you've read README to setup plugin correctly (there were some changes).
