### ISSUE TITLE
iOS crash during splash screen

### ISSUE THREAD

**Issue by Alb93** [chemerisuk/cordova-plugin-firebase-analytics#31]
Now the app crashes on iOS soon after the opening and nothing goes in output.

The GoogleService-Info.plist is well located in platforms/ios/{Project}/Resources and the app works good if this plugin is removed.

**Comment by chemerisuk** [comment]
Open project workspace in xcode, run app from there and paste your debug logs.

**Comment by Alb93** [comment]
This:

> Starting Firebase Analytics plugin
2017-06-26 00:30:09.318  <Error> [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.

But the file is inside platforms/ios/{Project}/Resources as you mentioned.

**Comment by chemerisuk** [comment]
Have you replace {Project} with your cordova project name?

**Comment by Alb93** [comment]
My first attempt was to put the file in platforms/ios/{Project}/Resources where {Project} was replaced by Bfaster, that is the app name.

After this failure, I tried to put the file I mean...everywhere.
I attach some screens:
![screen1](https://user-images.githubusercontent.com/11390668/27529533-35ba42da-5a55-11e7-8746-5fe14316a51d.jpg)
![screen2](https://user-images.githubusercontent.com/11390668/27529534-36d5e2b4-5a55-11e7-9fb0-3926ec9ac7f2.jpg)
![screen3](https://user-images.githubusercontent.com/11390668/27529535-37edb460-5a55-11e7-947e-ef5a3fb6ff04.jpg)
![screen4](https://user-images.githubusercontent.com/11390668/27529538-38fd5220-5a55-11e7-9009-b088215bfbbd.jpg)
![screen5](https://user-images.githubusercontent.com/11390668/27529540-39fc982a-5a55-11e7-8483-ec6f942f69ed.jpg)

Where am I wrong?

**Comment by chemerisuk** [comment]
Open you workspace in xcode. Do you see that file in Resource folder? If no, open context menu for Resources folder in xcode and click on the "Add files to ..." item.

**Comment by Alb93** [comment]
Ok so opening the project in this way bring to:
![screen6](https://user-images.githubusercontent.com/11390668/27533682-c1217474-5a64-11e7-8c06-2525507a047c.jpg)
in which no file is present.

So I've done this:
![screen7](https://user-images.githubusercontent.com/11390668/27533697-ce6d2718-5a64-11e7-8e03-aca303d2f656.jpg)

But now:
![screen8](https://user-images.githubusercontent.com/11390668/27533707-d9b7a576-5a64-11e7-8a13-26543b85dd40.jpg)

and the app is blocked with the splashscreen running and running.

**Comment by chemerisuk** [comment]
The plugin starts successfully, check other plugins setup.

**Comment by Alb93** [comment]
So the Firebase/core error soon after the plugin start is not related to the plugin?

**Comment by chemerisuk** [comment]
This is just a debug message, it's displayed in my projects too.

**Comment by NBAMj** [comment]
@Alb93 Have you tried to switch on `Keychain Sharing` from `Capabilities` tab?
The log in your screenshot mentions this: `Could not determine the app's default Keychain access group`

**Comment by prabhashibuddhima** [comment]
hi, have u solved the issue? I'm having the same
