### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by donuzium** [chemerisuk/cordova-plugin-firebase-analytics#33]
Like this issue there is a problem in the gradle file?
https://github.com/fechanique/cordova-plugin-fcm/issues/319

Android build failed with this error message.

```
* What went wrong:
A problem occurred configuring root project 'android'.
> Cannot add task ':processDebugGoogleServices' as a task with that name already exists.
```

It works when I changed a version 3.1.0 to 3.0.0.

**Comment by FdezRomero** [comment]
Your problem may be caused by other plugin dependencies in your app. With the PR you are proposing (#34) you might fix your individual problem but cause a new one to other people.

I had a similar problem in #32 and after removing and re-adding the Android platform it's now working. I would check that first.

**Comment by chemerisuk** [comment]
I feel like you have a conflict with some other plugin. 3.1.0 is the latest version of `com.google.gms:google-services` so I'm not sure it's right idea to downgrade it.

**Comment by donuzium** [comment]
@FdezRomero @chemerisuk 
Thanks for your fast reply. 

>Your problem may be caused by other plugin dependencies in your app. 
>I feel like you have a conflict with some other plugin

yes that's true. I installed just 2 plugins in new empty app.
cordova-plugin-fcm ('com.google.gms:google-services:3.0.0')
cordova-plugin-firebase-analytics ('com.google.gms:google-services:3.1.0')

> you might fix your individual problem but cause a new one to other people.
>I'm not sure it's right idea to downgrade it.

I think so too. I just want to tell my case. because there are not few users that use both firebase-related plugins.
Sorry, PR was exaggerated.

**Comment by donuzium** [comment]
>I had a similar problem in #32 and after removing and re-adding the Android platform it's now working. I would check that first.

I did remove and re-adding. But it doesn't work because of the conflict these versions.

**Comment by jonathan-chin** [comment]
I have the same issue as @donuzium 

I'm also using both this plugin and cordova-plugin-fcm

removing and adding the android platform again did not fix it for me.

what are some options?

**Comment by NBAMj** [comment]
I was having the same issue.
What I did is I changed a line in `project.properties` that corresponds to `play-services-ads` sdk version to use `11.0.+` explicitly
`cordova.system.library.1=com.google.android.gms:play-services-ads:11.0.+`

Hope it helps.

**Comment by PratikPagada** [comment]
open plugins directory -> build.gradle 

 Comment out these lines in the cordova-support-google-services directory build.gradle file.

 dependencies {
        classpath 'com.android.tools.build:gradle:2.2.1'     
     //  classpath 'com.google.gms:google-services:3.1.0'
    }

// ext.postBuildExtras = {
//     apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
// }

**then**  Remove and re-add plattform.

**then**
(build.gradle file of the android platform folder)
	Add this line to the classpath section

	classpath 'com.google.gms:google-services:3.1.0'
	And add this line below the dependencies, nearly at the bottom of the file
	apply plugin: 'com.google.gms.google-services'

**Comment by anuj-njoshi** [comment]
i also did removing installing android platform not work
