### ISSUE TITLE
setCurrentScreen vs logEvent('page_view')

### ISSUE THREAD

**Issue by kodeine** [chemerisuk/cordova-plugin-firebase-analytics#35]
as the title says, should they be both used or i should track current `page_view` via `setCurrentScreen`?

**Comment by JimDrury** [comment]
We're using `setCurrentScreen`, however Android is tracking in Firebase with `screen_view` events, yet iOS isnt.

**Comment by mustafamagdy2014** [comment]
@JimDrury would you please explain more ?
