### ISSUE TITLE
Support copying google-services.json and GoogleService-Info.plist to platforms/*

### ISSUE THREAD

**Issue by imgx64** [chemerisuk/cordova-plugin-firebase-analytics#36]
Now that cordova-plugin-firebase-hooks is deprecated, how should google-services.json and GoogleService-Info.plist be copied to the correct platform folder (and added as a Resource on iOS)? I know I can do it manually, but I prefer if things just worked out of the box.

**Comment by christoribeiro** [comment]
Any news here?

**Comment by chemerisuk** [comment]
Not going to be implemented. Add [resource-file](http://cordova.apache.org/docs/en/latest/config_ref/index.html#resource-file) tag into your `config.xml` with appropriate values. This is the right way to achieve this.

**Comment by rodrigograca31** [comment]
I almost opened another issue complaining about this... but @chemerisuk is correct. (gladly github related issues saved me!)

I still think it should have a hook or `cordova-support-google-services` should have the `resource-file` tag in that plugin....

For other wondering how to do it:
```xml
<platform name="android">
    <resource-file src="google-services.json" target="app/google-services.json" />
    ...
</platform>
<platform name="ios">
    <resource-file src="GoogleService-Info.plist" />
    ...
</platform>
```
[more documentation here](https://github.com/chemerisuk/cordova-support-google-services)
