### ISSUE TITLE
Question: How to configure firebase account?

### ISSUE THREAD

**Issue by danielcrk-cn** [chemerisuk/cordova-plugin-firebase-analytics#4]
This seems great and exactly what I'm looking for, but how do I configure the plugin to actually use my firebase account? I mean, where to provide project number, firebase url etc?

Feels like I might be missing something really obvious here.

**Comment by chemerisuk** [comment]
@danielcrk-cn just put your `google-services.json` and `GoogleService-Info.plist` into the root of your cordova app folder.

**Comment by danielcrk-cn** [comment]
@chemerisuk Thanks, I thought that might have been the case, but only since the other firebase blugin does this. Would be great if you mentioned it in te readme.

Thanks again!

**Comment by myspivey** [comment]
+1 on adding to the readme. Was not immediately clear where to add google services file.

**Comment by chemerisuk** [comment]
Fixed in 6fa0b858126844e22587d436a634702805332bfc
