### ISSUE TITLE
Missing google_app_id - GoogleServicesPlugin not running during build

### ISSUE THREAD

**Issue by oddcb** [chemerisuk/cordova-plugin-firebase-analytics#40]
Hi. So I've had problems getting the plugin to pick up the `google_app_id` from `google-services.json` in my ionic/cordova project. Tried removing/adding both the plugin and the platform to no avail. 

So I tried changing the content of the `platform/android/cordova-plugin-firebase-analytics/myprojectname-build.gradle`. Changes in the `buildScript` section would be picked up and give an error for the syntax error I introduced, but curiosly the ext.postBuildExtras {} section would not yield the same.

I moved the content of the file to the `build-extras.gradle` in the root of the platform and now the Google app id was picked up.

So.. does anyone have an idea why the buildscript from the plugin wouldn't execute?

**Comment by chemerisuk** [comment]
@oddcb https://github.com/chemerisuk/cordova-support-google-services#installation
