### ISSUE TITLE
FirebaseAnalytics not found on IOS

### ISSUE THREAD

**Issue by kodeine** [chemerisuk/cordova-plugin-firebase-analytics#41]
i have this error after build.

Plugins/cordova-plugin-firebase-analytics/FirebaseAnalyticsPlugin.m:2:9: Module 'FirebaseAnalytics' not found

any idea whats going on?

**Comment by maxbye3** [comment]
HI @kodeine,
I just solved this and got it sorted by following this guide:
https://firebase.google.com/docs/ios/setup#initialize_firebase_in_your_app
In my case go to xcodeproj directory and run:
`$ pod install`
