### ISSUE TITLE
No Stats on IOS - success call being returned but returned object is always null

### ISSUE THREAD

**Issue by n40jpj** [chemerisuk/cordova-plugin-firebase-analytics#43]
Great plugin, and very easy to follow setup steps, am I missing something though as I can not get any stats on firebase console analytics.

The calling code is 

`    this.firebaseAnalytics
      .logEvent("page_view", { page: "dashboard" })
      .then((res: any) => console.log("one", res))
      .catch((error: any) => console.error(error));
`

the res value always comes back as null.

I have checked through my solution a number of times looking for a typo but can't find anything.  I have included FirebaseAnalytics in my providers list within the app.module.ts.

**Comment by jaybloke** [comment]
Got a similar problem - Firebase is actually collecting data, however the then/catch is never called:

```
this.firebaseAnalytics.logEvent("page_view", { page: "Jobs" })
  .then(
    (response: any) => {
      console.log('entered');
    }
  )
  .catch(
    (error: any) => {
      console.log(error);
    }
  )

```

Same thing applies to setCurrentScreen(...)

**Comment by sahyun1** [comment]
same here, it works fine on android but not on ios..just like @n40jpj 's problem

**Comment by sahyun1** [comment]
ok what I did to solve the issue,

I delete the node_modules, npm cache clean and npm install
and clean pods cache

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

if xCode complains about linker issue, then do pod install.

I don't know specifically which bit fixed the issue, but hopefully this is helpful
