### ISSUE TITLE
Ionic app crash: unfortunately, App has stopped.

### ISSUE THREAD

**Issue by fujahgabriel** [chemerisuk/cordova-plugin-firebase-analytics#44]
I was able to build my app but when I try installing it on an android device I get the following error "unfortunately, App has stopped." 
Once I rm firebase analytics plugin the app works fine.

Pls help its urgent

**Comment by mobyjames** [comment]
Likely due to `google-services.json` not found. Connect the device and monitor the output log for details.

**Comment by fujahgabriel** [comment]
@mobyjames where should it be? I added it to the android folder

**Comment by danelse** [comment]
@fujahgabriel 
Copy google-services.json to your app root directory and add the following code to your config.xml:
`
...
<platform name="android">
  ...
  <resource-file src="google-services.json" target="google-services.json" />
`

**Comment by chemerisuk** [comment]
@bfujahgabriel do you have `google-services.json` and `GoogleService-Info.plist` at the right folders?

https://github.com/chemerisuk/cordova-support-google-services#installation

**Comment by fujahgabriel** [comment]
yes i do. same issue

**Comment by thomasblom** [comment]
I use this plugin in combination with capacitor, but it can't find the `.plist` file. Can I somehow force the location to look for the file?
