### ISSUE TITLE
Could not find any version that matches com.google.firebase:firebase-core

### ISSUE THREAD

**Issue by JimJty** [chemerisuk/cordova-plugin-firebase-analytics#45]
Got this message when trying to build for android:

    Could not find any version that matches com.google.firebase:firebase-core:11.0.+.

I had to update my Google Repository in the Android SDK manager to latest. Just FYI in case anyone else runs into the same issue (could be added to the FAQ in the README). Thanks for the plugin!

**Comment by chemerisuk** [comment]
Check your setup to find which version is used in your project. In the latest version you can use `FIREBASE_VERSION` to set a specific dependency version:

```
cordova plugin add cordova-plugin-firebase-analytics --save --variable FIREBASE_VERSION=11.6.0
```

**Comment by rja-majconsulting** [comment]
Same kind of problem even after setting a specific FIREBASE_VERSION like proposed.
Got this message when trying to build for android:
`Could not get unknown property 'FIREBASE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`
