### ISSUE TITLE
Failed to apply plugin  com.google.gms.googleservices.GoogleServicesPlugin  For input string +

### ISSUE THREAD

**Issue by mustafamagdy2014** [chemerisuk/cordova-plugin-firebase-analytics#46]
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

**Comment by ycanales** [comment]
I have the same error, did you solve it?

**Comment by ycanales** [comment]
Solved it with https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/33#issuecomment-337136340
