### ISSUE TITLE
processArmv7DebugGoogleServices Error

### ISSUE THREAD

**Issue by lfelipeqn** [chemerisuk/cordova-plugin-firebase-analytics#47]
I'm getting the following error each time I try to run the app in an android device

"What went wrong:
Execution failed for task ':processArmv7DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.0."

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#faq

**Comment by rubenstolk** [comment]
Shouldn't there be a way to get this working with `com.android.tools.build:gradle:2.3.3+`?

**Comment by chemerisuk** [comment]
@rubenstolk Works with `com.android.tools.build:gradle:+` on my side
