### ISSUE TITLE
App has stopped

### ISSUE THREAD

**Issue by harsinh** [chemerisuk/cordova-plugin-firebase-analytics#48]
HI 
I am trying to implement firebase analytics in our hybrid app . Configurations are --
node  4.2.1,   ionic 2.0.0,   cordova 5.3.3

->added $ cordova plugin add cordova-plugin-firebase-analytics
->I have made sure to add google-service.json file 
->Made appropriate changes in build.gradle (  classpath 'com.google.gms:google-services:3.1.0') 

the build is successful after these settings , but the moment I launch this app in android device 
error comes  App has stopped.

I was successful in implementing google analytics with cordova plugin , but there seems to be something in firebase plugin which kills the app (may be compatibility).

Please help .....

**Comment by lfelipeqn** [comment]
I tried to replicate the steps you followed in order to achieve a successful build. But got this instead:

**A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
  > For input string: "+"**

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#faq

**Comment by lfelipeqn** [comment]
Still unable to make it work altough we are using the following plugins

com.googlemaps.ios 2.3.0 "Google Maps SDK for iOS"
cordova-clipboard 1.0.0 "Clipboard"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoapod-support 1.3.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-firebase-analytics 0.11.0 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.0.0-beta3-20170903-1743 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.3 "Cordova sqlite storage plugin"
cordova-support-google-services 1.0.0 "cordova-support-google-services"
ionic-plugin-keyboard 2.2.1 "Keyboard"
org.apache.cordova.plugin.cache 1.0.5 "Clear Cache"

**Comment by harsinh** [comment]
HI 

I tried the steps --

--$ cordova plugin add cordova-support-google-services --save
--applied necessary changes in build.gradle file 
but the app again stopped .

**Comment by harsinh** [comment]
@lfelipeqn  please try 
->cordova platform rm android 
->cordova platform add android@5.0.0
 ->then make changes in build.gradle file again .

**Comment by analytics-jiten** [comment]
@chemerisuk 

Hey Chemerisuk,

First of all great work done. Many Thanks in Advance.

As we are using cordova (5,3,3) and ionic framework (2.0.0), we are installing plug-in cordova-plugin-firebase-analytics as explained in the support document.

Post installing plug-in, we have done all the changes in build.gradle file and have added google-services.json file. When we are compiling the code and making the build, the build is running successfully but the moment app is launching, it is getting killed on boot.

We do have following queries as well:

1. When we check the path/directory configuration in the js file then it is referring to the google-services.json file of "/myproject/platform/android/src/google-services.json" which is root folder of the app and one more blank google-services.json file is being created automatically by plug-in installed under plug-in folder which is "/plugins/cordova-plugin-firebase/android/src/google-services.json". Now we are confuse which google-services.json file is actually being referred by the app and which one to be updated. Please shred some light here.

Also, our Android SDK version is 23. Is there any dependencies or upgrade issues ?
