### ISSUE TITLE
Measurement Service called without google_app_id

### ISSUE THREAD

**Issue by FdezRomero** [chemerisuk/cordova-plugin-firebase-analytics#5]
Hello @chemerisuk,

First of all, thanks for the plugin. I have downloaded and added `google-services.json` to the root folder and the build is successful, but when I check the logs using the Android Monitor I get these errors:

```
11-16 12:29:50.335: E/FA(23669): GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.
11-16 12:29:50.335: E/FA(23669): Scheduler not set. Not logging error/warn.
11-16 12:29:50.344: E/FA(23669): Measurement Service called without google_app_id
11-16 12:29:50.346: E/FA(23669): Uploading is not possible. App measurement disabled
```

I checked that `google-services.json` is correctly copied to `platforms/android/google-services.json`. Any idea of what may be causing this error?

Thanks

**Comment by FdezRomero** [comment]
Reinstalling the plugin with `google-services.json` already present seems to have fixed the issue. Closing.

**Comment by robations** [comment]
@FdezRomero (or anyone). I tried:

```
cordova plugin remove cordova-plugin-firebase-analytics
cordova plugin add cordova-plugin-firebase-analytics
```

but I still have this error coming from adb logcat. Do I need to do anything with the `GoogleService-Info.plist` file, other than leave in the project root? I sort of expected this file to be copied somewhere into platforms/android but I don't see that happening.

**Comment by FdezRomero** [comment]
@robations `GoogleService-Info.plist` is for iOS, Android needs `google-services.json` from the root project directory. Maybe that's your problem?

**Comment by robations** [comment]
@FdezRomero Thanks for your reply. I think the holidays were too long — of course the `plist` file is for iOS, ignore that comment. And I already have this working for iOS.

So I do have the file `platforms/android/google-services.json`, as set up by cordova-plugin-firebase-hooks, but still getting the error message `Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI`. I'll continue to look for clues.

**Comment by FdezRomero** [comment]
In my case the file was also at the right locations, but it wasn't picked up by Firebase. Reinstalling the plugin solved my issue. Sorry I can't be of more help!

**Comment by robations** [comment]
The only extra information I can add at the moment is that the [Android Firebase docs](https://firebase.google.com/docs/android/setup) say to add this line to your gradle file:

    apply plugin: 'com.google.gms.google-services'

I can see this line in firebase-hooks, in `build-extras.gradle`, but not under `platforms/android` (I searched with recursive grep).

**Comment by pablo-gonzalez** [comment]
Hi. I am facing the same issue.

I am using Ionic framework to create a test application.
I put the google-services.json file in the root folder. Once the build is made the file is copied to platforms/android as expected without errors.

I left the json file in folder as advised and then removed the plugin and android platform.
After reinstalling platform and plugin same results :(

```
adb logcat -v time | grep Firebase

01-23 18:22:38.840 I/FirebaseInitProvider(19839): FirebaseApp initialization unsuccessful
01-23 18:22:39.681 D/FirebaseAnalyticsPlugin(19839): Starting Firebase Analytics plugin
01-23 18:22:39.711 E/FA      (19839): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
01-23 18:22:42.395 W/FA      (19839): Failed to retrieve Firebase Instance Id
01-23 18:22:42.396 E/FA-SVC  ( 2026): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
```

```
adb logcat -v time | grep GoogleService
01-23 18:22:39.700 E/FA      (19839): GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.

```

Am I missing anything?
Is google_app_id one of the entries in google-services.json?
Where is Firebase initialization trying to get that value from?

Thanks in advance, 
Pablo

**Comment by danielgomezrico** [comment]
It happened to me after I called 1 time `analytics.setAnalyticsCollectionEnabled(false);`.

I thought this just pause this while the app is alive, after I uninstalled it and install it again it works fine.
