### ISSUE TITLE
Firebase SDK conflicts with (FCM and Firebase Analytics)

### ISSUE THREAD

**Issue by mailtoamirjohn** [chemerisuk/cordova-plugin-firebase-analytics#51]
Using following plugins together. 

cordova-plugin-fcm ,

cordova plugin add cordova-plugin-firebase-analytics --save

and cordova plugin add cordova-plugin-googleplus.

**ISSUE:** After adding all the plugins FCM notification not works.

But all the three plugin works fine independent projects.

**Getting some conflicts after integrating together.**

I think some problem in different version of firebase and google plugin.

**Comment by airstep** [comment]
+1 same

**Comment by HeatherWolford** [comment]
I am also experiencing the same.  

When I run:
cordova build android
I get the following:
What went wrong: A problem occurred configuring root project android. Cannot add task :processDebugGoogleServices' as a task with that name already exists.

I am attempting to use Firebase Analytics (cordova-plugin-firebase-analytics) which requires the plugin, Google Services (cordova-support-google-services). I am also using Firebase Cloud Messaging (cordova-plugin-fcm). The cordova-plugin-fcm includes Google Services 3.0.0 and the cordova-support-google-services has Google Services at 3.1.0 creating the conflict.

I am new to using Ionic 3/Angular 4. A fix I had found on a different forum, and implemented, was changing the version in platforms/android/cordova-support-google-services to 3.0.0 from 3.1.0. This was only a temporary fix, and a Sr. Dev on my team said this was terrible and should never be done. Of course, I do not want to do something that is a bad practice, however, what this error informed me of is that if I can get the dependencies at the same version, then the conflict resolves and the project builds.

Any guidance you can offer would be extremely helpful.

Thank you!

**Comment by chemerisuk** [comment]
The conflict will be fixed after merging of https://github.com/fechanique/cordova-plugin-fcm/pull/495

**Comment by dimitri320** [comment]
Conflict was not fixed! I'm still getting it....

**Comment by Saloni3187** [comment]
There is google play services compatibility issue with both the plugins.
Has anybody find the solution for the same.
