### ISSUE TITLE
Feature reqyuest:  add support for Firebase Crashlytics

### ISSUE THREAD

**Issue by jaufgang** [chemerisuk/cordova-plugin-firebase-analytics#52]
Firebase has recently announced that Crashlytics will be their new error reporting platform.  Do you have any plans to add the crashlytics API to this plugin in the near future?

**Comment by chemerisuk** [comment]
No plans for now, anyway it should be done in a separate repository.

**Comment by FranciscoG** [comment]
I forked this project and slowly converting into a Crashlytics plugin.  iOS only for now but eventually will try android. I have yet to test it out, still in the early stages 

https://github.com/FranciscoG/cordova-plugin-firebase-crashlytics

**Comment by chemerisuk** [comment]
@FranciscoG @jaufgang I'm planning to update https://github.com/chemerisuk/cordova-plugin-firebase-crash to use Chashlytics SDK.

**Comment by FranciscoG** [comment]
@chemerisuk awesome! because I'm having difficulty getting it to work so I'll just wait for your update. 
thanks!

**Comment by chemerisuk** [comment]
@jaufgang @FdezRomero try 0.12.0 of https://github.com/chemerisuk/cordova-plugin-firebase-crash
