### ISSUE TITLE
Cocoon.io build error

### ISSUE THREAD

**Issue by gametrick** [chemerisuk/cordova-plugin-firebase-analytics#53]
Build error when using Cocoon.io service. Could you please help?

----------

COMPILER ERROR: 

/workspace/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script '/workspace/platforms/android/cordova-support-google-services/global-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CORDOVA LOG: 

[36m[2017-11-09 08:18:25.541] [DEBUG] AndroidBuilder - [39m[prepare] cordova restore platforms
[36m[2017-11-09 08:18:25.554] [DEBUG] AndroidBuilder - [39m[prepare] adding engine android@6.2.3
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
Subproject Path: CordovaLib
[36m[2017-11-09 08:18:38.481] [DEBUG] AndroidBuilder - [39m[prepare] cordova restore plugins
[36m[2017-11-09 08:18:38.483] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cocoon-plugin-share@*
[36m[2017-11-09 08:18:38.528] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.defaultres.android@1.0.1
[36m[2017-11-09 08:18:38.581] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.usericon.android@1.0.1
[36m[2017-11-09 08:18:38.641] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.usersplash.android@1.0.2
[36m[2017-11-09 08:18:38.685] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.webviewplus.android@2.2.1
[36m[2017-11-09 08:18:38.730] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin com.ludei.webviewplus.ios@1.1.0
[36m[2017-11-09 08:18:38.796] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-admobpro@2.29.24
[36m[2017-11-09 08:18:38.829] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-firebase-analytics@*
[36m[2017-11-09 08:18:38.861] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-inappbrowser@*
[36m[2017-11-09 08:18:38.907] [DEBUG] AndroidBuilder - [39m[prepare] adding plugin cordova-plugin-whitelist@*
[36m[2017-11-09 08:18:40.510] [DEBUG] AndroidBuilder - [39m[build]
[36m[2017-11-09 08:18:40.511] [DEBUG] AndroidBuilder - [39m[build] create certs folder
[36m[2017-11-09 08:18:40.511] [DEBUG] AndroidBuilder - [39m[build] keystore
[36m[2017-11-09 08:18:40.707] [DEBUG] AndroidBuilder - [39m[build] create release build.json
[36m[2017-11-09 08:18:40.708] [DEBUG] AndroidBuilder - [39m[build] call cordova
ANDROID_HOME=/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Subproject Path: CordovaLib
Starting a Gradle Daemon, 17 stopped Daemons could not be reused, use --status for details
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_50oro7zaoq1sb73fozu0qul8z.run(/workspace/platforms/android/build.gradle:140)
org.xwalk:xwalk_core_library:22+
Not writing assets/xwalk-command-line since file already exists.

FAILURE: Build failed with an exception.

* Where:
Script '/workspace/platforms/android/cordova-support-google-services/global-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.32 secs

**Comment by chemerisuk** [comment]
@gametrick https://github.com/chemerisuk/cordova-support-google-services#build-error-failed-to-apply-plugin-class-comgooglegmsgoogleservicesgoogleservicesplugin
