### ISSUE TITLE
Implementation of GTM along with Cordova Firebase Analytics Plug-In

### ISSUE THREAD

**Issue by analytics-jiten** [chemerisuk/cordova-plugin-firebase-analytics#54]
Hi There,

Recently we have installed cordova firebase analytics plug-in and we are able to get the hits in our firebase account but we would like implement GTM container in the app so that we can manage each and everything via GTM whenever we want to fire an additional event.

Can someone please guide if we can implement GTM along with this plug-in. If yes, then what is the process.

**Comment by chemerisuk** [comment]
I'm planning to investigate this, but no timestamps for now.

**Comment by chemerisuk** [comment]
Check [gtm branch](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/tree/gtm)

**Comment by juliosampaio** [comment]
Hey @chemerisuk by simple downloading this branch the integration should work? Or Is there any other configuration that should be done?

**Comment by edvenkat** [comment]
@analytics-jiten @chemerisuk @juliosampaio @jonas-m- @FdezRomero 

Hi Guys how to link GTM and App. can you please advice????

**Comment by hvaughan3** [comment]
@edvenkat I ended up forking the main branch and implementing the same changes that were made in the [GTM branch](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/tree/gtm)

**Comment by edvenkat** [comment]
@hvaughan3 what are the things need to set up in GTM console and can i use same function for screen view and events logging

**Comment by edvenkat** [comment]
@hvaughan3 i m using gym branch and same js
Function without setup the GTM but i can see event logging in firebase then what the use of GTM console

**Comment by hvaughan3** [comment]
@edvenkat Yea I wonder that myself... One thing that I know it can do is to forward your Firebase events to a Google Analytics account. It can also modify the events and trigger new events based on what is sees from firebase.

I have yet to see an example of being able to dynamically create new events through Firebase Analytics, which I thought was the main point of GTM.

**Comment by edvenkat** [comment]
@hvaughan3 By default all the data collected in Firebase. we can transfer the data from Firebase to GA using GTM if you need. is right?

**Comment by hvaughan3** [comment]
@edvenkat It is not be default, you have to choose the Firebase events and setup a trigger to send them to GA.

**Comment by edvenkat** [comment]
@hvaughan3 GTM branch is working in android but not in ios can you please advice??

**Comment by hvaughan3** [comment]
@edvenkat I assume you included separate *GTM-XXXX.json* files for iOS and Android as `<resources>`? Are there any messages in the log?

**Comment by edvenkat** [comment]
Yes @hvaughan3 i have used like below

```
<platform name="ios">
	<resource-file src="GoogleService-Info.plist" />
	<resource-file src="GTM-TGT4ZB4.json" /> 
</platform>


```

**Comment by hvaughan3** [comment]
@edvenkat Any Google Tag Manager related log messages when you run the app?

**Comment by edvenkat** [comment]
@hvaughan3 No i couldn't see. i am using phonegap build site to generate apk and ipa files. any other idea.

**Comment by hvaughan3** [comment]
@edvenkat You should still be able to look in the console window when you run the app right?

**Comment by edvenkat** [comment]
@hvaughan3 console window mean GTM or GA ?

**Comment by edvenkat** [comment]
@hvaughan3 Also checked in your GTM branch. i am using the same code. 
https://github.com/hvaughan3/cordova-plugin-firebase-analytics/tree/gtm

**Comment by hvaughan3** [comment]
@edvenkat No the simulator or iOS device console window.

**Comment by edvenkat** [comment]
@hvaughan3 i am testing in device. can you share your skype id if you have

**Comment by hvaughan3** [comment]
@edvenkat Hook up your device to your computer and view the console output when you run the app.

**Comment by edvenkat** [comment]
@hvaughan3 install the app using phonegap build i dont know how to debug can you explain please

**Comment by edvenkat** [comment]
@hvaughan3 i didn't see any error in console

**Comment by edvenkat** [comment]
@hvaughan3 where we need to move the file "GTM-XXXXX/json"  project_root or project_root/container 

https://developers.google.com/tag-manager/ios/v5/

**Comment by hvaughan3** [comment]
@edvenkat I put mine in the root of my Cordova project. Then the `<resource>` tag moves it into the correct place.

**Comment by edvenkat** [comment]
@hvaughan3 can you share the resource tag in document need to move the GTM-xxx.json file to   container folder. Please refer 

https://developers.google.com/tag-manager/ios/v5/

**Comment by hvaughan3** [comment]
@edvenkat Using the `<resource-file>` tag as you had them was correct:

<platform name="ios">
	<resource-file src="GoogleService-Info.plist" />
	<resource-file src="GTM-TGT4ZB4.json" /> 
</platform>

**Comment by edvenkat** [comment]
@hvaughan3 but this resource tag move file to project root not container folder... In above link, please see the point  download json and move to container folder or it is working from root

**Comment by hvaughan3** [comment]
@edvenkat It is better to put it in resources folder but it can still be found in the root. It is working in the root for me.

**Comment by edvenkat** [comment]
@hvaughan3 can you please share your code

**Comment by hvaughan3** [comment]
@edvenkat You have the forked plugin code from my repo and your `<resource-file>` tags are identical to mine. Thats really all the code there is for it. I am using straight Cordova though, not PhoneGap.

I assume Firebase is working in your app? If so that should be all you need to do other than setting things up in the GTM website.

**Comment by edvenkat** [comment]
@hvaughan3 i will with you repo. For android every thing working fine but ios events are logging in firebase but not in GTM

**Comment by hvaughan3** [comment]
@edvenkat Make sure to allow the Google URLs in config.xml and index.html's CSP, but I would imagine that if Firebase is not being blocked, then GTM wouldn't be blocked either.

    <access origin="https://www.google-analytics.com" />
    <access origin="https://www.google.com" />

**Comment by edvenkat** [comment]
@hvaughan3 thanks will check and update you 😁

**Comment by edvenkat** [comment]
@hvaughan3 i have added th access origin but still it is not working. but i am using below version for both firebase core and gtm. is this fine??

 ```
 <framework src="Firebase/Core" type="podspec" spec="~> 4.1"/>
  <framework src="GoogleTagManager" type="podspec" spec="~> 6.0"/>
```

**Comment by hvaughan3** [comment]
@edvenkat Yea but you could also try:

    <framework src="Firebase/Core" type="podspec" spec="~> 5.6"/>
    <framework src="GoogleTagManager" type="podspec" spec="~> 7.0"/>

**Comment by edvenkat** [comment]
@hvaughan3 i saw. Any problem with different version

**Comment by edvenkat** [comment]
> @edvenkat Actually I am using:
> 
> ```
> <framework src="Firebase/Core" type="podspec" spec="~> 5.6"/>
> <framework src="GoogleTagManager" type="podspec" spec="~> 7.0"/>
> ```
> [Link](https://github.com/hvaughan3/cordova-plugin-firebase-analytics/blob/master/plugin.xml#L34)

test
