### ISSUE TITLE
Needs a Changelog

### ISSUE THREAD

**Issue by prantikv** [chemerisuk/cordova-plugin-firebase-analytics#57]
Hey there,
I came back to this plugin after a month and there were come upgrades. The plugin now supports cordova-android >6.0.

This is flashed in the CLI. But there is no mention of this in the docs.

Also, I wanted to revert back to a previous version but could not find it as there is no change log.

Thanks

**Comment by rodrigograca31** [comment]
Agreed but keeping it up to date its a burden that no one wants..........
I usually use the releases tags to see the commits that are in a certain release and that's a good enough changelog....

[Example for v2.0.0 here](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/compare/v2.0.0...master)
