### ISSUE TITLE
Needs Firebase standalone implementation? ("unfortunately, App has stopped")

### ISSUE THREAD

**Issue by baztypetrucci** [chemerisuk/cordova-plugin-firebase-analytics#60]
Hi, I'm trying to install this plugin, but I have the same errors than others Issues.

I Followed all the instructions.
1- https://ionicframework.com/docs/native/firebase-analytics/
2- Installed cordova-support-google-services
3- Modified the graddle.build

The build has completed successfully. But the app still crashing.

Questions:

- Where I can find logs for this kind of error?
- It's needed Firebase standalone installation (Firebase + Firebase analytics + Google services)?

Thank you so much!

**Comment by chemerisuk** [comment]
@baztypetrucci do you have `google-services.json` and `GoogleService-Info.plist` at the right folders?

https://github.com/chemerisuk/cordova-support-google-services#installation
