### ISSUE TITLE
IOS Build Error : Module FirebaseAnalytics not found

### ISSUE THREAD

**Issue by royken** [chemerisuk/cordova-plugin-firebase-analytics#61]
Hello, I'm trying to build the project after adding the plugins and i have an error saying "module FirebaseAnalytics not found" (in FirebaseAnalytics.m file)

### Steps to reproduce : 
- add plugin to project :  `cordova plugin add cordova-plugin-firebase-analytics`
- Open in XCODE and make build

Ionic V1

**Comment by franciswagner** [comment]
Having the same problem here on ionic v1 too.

**Comment by chemerisuk** [comment]
Try 0.13.0

**Comment by AniciusM** [comment]
Well its working fine with pod version 1.4.0
