### ISSUE TITLE
project.properties not updated using FIREBASE_VERSION when adding Android platform

### ISSUE THREAD

**Issue by jholzer-cciq** [chemerisuk/cordova-plugin-firebase-analytics#65]
In my config.xml, I have the following configuration for the `cordova-plugin-firebase-analytics` plugin:
```
<plugin name="cordova-plugin-firebase-analytics" spec="^0.12.1">
    <variable name="FIREBASE_VERSION" value="11.6.2" />
</plugin>
```

However, when I run `cordova platform add android` the resulting `project.properties` file for the Android project is generated referencing the wrong version of the `firebase-core` library (11.0.+):
```
cordova.system.library.4=com.google.firebase:firebase-core:11.0.+
```

It seems like the `FIREBASE_VERSION` variable is not utilized properly, or have I configured something incorrectly?

**Versions:**
`cordova-cli`: 8.0.0
`cordova-android`: 7.0.0
`cordova-plugin-firebase-analytics`: 0.12.1

**Comment by chemerisuk** [comment]
Could be a problem with `cordova platform add android`. `cordova plugin add` works correctly with variables.

**Comment by jholzer-cciq** [comment]
@chemerisuk FWIW, I made the following changes, which resolved the issue:
- in `package.json`, set `FIREBASE_VERSION` property for plugin to 11.6.2
- upgraded cordova-android platform to 7.1.0
- refreshed android project by running `cordova platform rm android` followed by `cordova platform add android@7.1.0`
