### ISSUE TITLE
This is not supporting crashlytics

### ISSUE THREAD

**Issue by vishwasvogga** [chemerisuk/cordova-plugin-firebase-analytics#66]
As given in the plugin desriptions this should have supported fire base crashlytics , but it is not. My fire base crashlytics is still asking to install SDK (native android) and crash in my ionic app is not reflected in firebase crashlytics console , Plese help.

**Comment by chemerisuk** [comment]
Use https://github.com/chemerisuk/cordova-plugin-firebase-crash

**Comment by vishwasvogga** [comment]
Thanks man! But is there any ionic plugin? above one is cordova plugin?.
