### ISSUE TITLE
setUserProperties method is not working

### ISSUE THREAD

**Issue by ravikumarthuta** [chemerisuk/cordova-plugin-firebase-analytics#67]
i send user properties to the firebase using setUserProperty(name, value). Here i got the success but when i go to the firebase and check the events filter i am not getting any user properties. please suggest me.

**Comment by chemerisuk** [comment]
You have to add user properties in firebase console first.

**Comment by ravikumarthuta** [comment]
Hi,
I already registered in fire base. my registered keys are show in events
filter but value is not showing.please help me .

Thanks&Regards,
Ravikumar .

On Fri, Apr 20, 2018 at 4:33 PM, Maksim Chemerisuk <notifications@github.com
