### ISSUE TITLE
Fails to install with plugman

### ISSUE THREAD

**Issue by trustedjohn** [chemerisuk/cordova-plugin-firebase-analytics#68]
I'm using the cordova ios platform build tools for my project (cli version 8.0.0).

The plugin installs and runs fine when using "cordova plugin" command, but when I use the appropriate "plugman install ..." method, the command fails prematurely resulting in a broken build.  Note that Plugman correctly installs cordova-support-google-services plugin (along with all my other plugins), so the problem appears to be specific to this plugin's interaction with Plugman - specifically a failure during the pod install process (observed when adding the "-d" to the command below):

```
johnk@FastJohnny2:/Developer/Code/atest/platforms/ios$ sudo plugman install --platform ios --project . --plugin cordova-plugin-firebase-analytics
Fetching plugin "cordova-plugin-firebase-analytics" via npm
Installing "cordova-plugin-firebase-analytics" for ios
Failed to install 'cordova-plugin-firebase-analytics': undefined
undefined
```
Trying to build the project after this results in an error about missing Firebase module. Subsequently using Plugman to uninstall the plugin also results in an "undefined" output.

**Comment by kodeine** [comment]
same error, any fix?
