### ISSUE TITLE
IonicPro: ld: library not found for -lGoogleToolboxForMac

### ISSUE THREAD

**Issue by Chinchilla86** [chemerisuk/cordova-plugin-firebase-analytics#70]
Hi,

I have an issue with `cordova-plugin-firebase-analytics` on my local machine and in Ionic Pro creating a package.

That's the error from building a package in Ionic Pro for iOS and running `ionic cordova run ios --device --release` on my local machine:
```
❌  ld: library not found for -lGoogleToolboxForMac
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here ara my local setup of Ionic:
```
cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
System:
    Node : v9.3.0
    npm  : 5.6.0
    OS   : macOS Sierra
Misc:
    backend : pro
```

Locally, I can build the package multiple times and eventually it will work. But that's not possible in Ionic Pro.
Do you have any suggestions to solve this problem?

**Comment by maxs15** [comment]
Same issue.. did you find a way to fix it ?

Thanks

**Comment by Chinchilla86** [comment]
@maxs15 
Sadly, not. My solution was to switched to https://ionicframework.com/docs/native/firebase/
I'm only using the logEvent()-Method. Therefore `cordova-plugin-firebase-analytics` was the more suitable plugin.

**Comment by Chinchilla86** [comment]
@maxs15
Today I found the following hint: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#library-not-found-for--lgoogletoolboxformac
I did not try it out. Maybe it'll help for local use. For the build process of Ionic Pro it's not relevant, because you can't change it.

**Comment by michalakjan** [comment]
@Chinchilla86 
I've tried it, and yes for local usage this works

```
cd platforms/ios
pod install
```

i've also have some problems with firebase versions, so i need to set it like that

```
      "cordova-plugin-firebase-analytics": {
        "FIREBASE_VERSION": "11.8.0"
     }
```

but as you mention its not relevant for ionic pro build process
