### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by jellomaster** [chemerisuk/cordova-plugin-firebase-analytics#74]
In order for the plugin to better comply with GDPR you should change it so one can set setAnalyticsCollectionEnabled to false.  It's true by default so either change the setEnabled function to allow passing true/false or make a setDisabled function.
See more:
https://support.google.com/firebase/answer/9019185?hl=en

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-plugin-firebase-analytics#setenabledenabled Already accepts Boolean parameter
