### ISSUE TITLE
How to fix Error: Duplicate resources when generate android build

### ISSUE THREAD

**Issue by vaishalivc** [chemerisuk/cordova-plugin-firebase-analytics#78]
What is the solution for that error or because of which plugin it may happen when generating build, any idea ?
Please help me to fix it..

BUILD FAILED in 1s
(node:4868) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':app:mergeDebugResources'.

    [string/google_app_id] ........\platforms\android\app\src\main\res\values\strings.xml [string/google_app_id] ............\platforms\android\app\build\generated\res\google-services\debug\values\values.xml: Error: Duplicate resources
    [string/google_api_key] ..............\platforms\android\app\src\main\res\values\strings.xml [string/google_api_key] ................\platforms\android\app\build\generated\res\google-services\debug\values\values.xml: Error: Duplicate resources

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    Get more help at https://help.gradle.org

BUILD FAILED in 1s
at ChildProcess.whenDone (....................\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
at ChildProcess.emit (events.js:160:13)
at maybeClose (internal/child_process.js:943:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:4868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jvjvjv** [comment]
It sounds like it may be an issue with conflicting plugins. Please provide your plugin list.

**Comment by vaishalivc** [comment]
@jvjvjv , Here i used the plugin which is listed below:

ionic cordova plugin add cordova-plugin-firebase
ionic cordova platform add android
ionic cordova platform add ios
->"angularfire2": "^5.0.0-rc.6",
->"firebase": "^5.0.4",

**Comment by jvjvjv** [comment]
Just the output of `ionic cordova plugin list` will do, thanks.

**Comment by vaishalivc** [comment]
okay, Thank you for suggestion @jvjvjv , Here is my list:

cordova-android-play-services-gradle-release 1.4.2 "cordova-android-play-services-gradle-release"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-firebase-authentication 0.14.0 "cordova-plugin-firebase-authentication"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-android-plugin 0.3.7 "cordova-support-android-plugin"
cordova-support-google-services 1.1.0 "cordova-support-google-services"

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#duplicate-resources-platformsandroidbuildgeneratedresgoogle-servicesarmv7debugvaluesvaluesxmlstringgoogle_api_key-platformsandroidresvaluesstringsxmlstringgoogle_api_key

**Comment by vaishalivc** [comment]
@chemerisuk I'll try to delete that key's manually from file but when i re-run for build it auto generate that key's again and through same error.

**Comment by vaishalivc** [comment]
@chemerisuk , Here is my updated plugin list:

cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
phonegap-plugin-push 2.1.3 "PushPlugin"

**Comment by chemerisuk** [comment]
Probably this one: cordova-plugin-firebase

**Comment by vaishalivc** [comment]
@chemerisuk , So what is the possible solution for that, i'll ask it because i'll try to change/hide in: cordova-plugin-firebase - ".xml" file but not get any change in error.

**Comment by romanovma** [comment]
+1
I started experiencing same issue about a week ago with cordova-plugin-firebase. 
Before it was fine.

**Comment by jvjvjv** [comment]
My suggestion (sorry @chemerisuk) is to stich with cordova-plugin-firebase if you need all of the integrations it provides.

This plugin would already replicate functionality contained in the former, so there is no need for both.

**Comment by vaishalivc** [comment]
@chemerisuk  @jvjvjv , i need this plugin "phonegap-push-plugin" and i try to remove this one "cordova-plugin-firebase", not completely remove that plugin,  also getting error , step by step resolve all the error and again stuck in same issue which i posted, so what i suppose to do??

**Comment by jvjvjv** [comment]
@vaishalivc If you integrate Firebase notifications you can use cordova-plugin-firebae, so you no longer need phonegap-push-plugin nor its dependency.

**Comment by vaishalivc** [comment]
@jvjvjv Push notification in ionic fire-store is totally new for me, so i'll find a documentation that used "phonegap-push-plugin" and try to implement it.

**Comment by vaishalivc** [comment]
@chemerisuk , @jvjvjv, @romanovma  Hey everyone, i'll get the solution for this problem. Here need to delete google_app_id & google_api_key from android.json file, then after when you generate build its successfully generated !! Thank you for responce.

**Comment by tmk1991** [comment]
@vaishalivc  Where are those keys? I can't locate them in my google-services.json from firebase. @chemerisuk  have you considered working with @soumak77 to align with cordova-plugin-firebase?

**Comment by vaishalivc** [comment]
@tmk1991 as i said, that keys are located in android.json file.

**Comment by NagendraMNK** [comment]
If your using firebase console then google service plist and json replace that from firebase configured files

**Comment by kapilSoni101** [comment]
@vaishalivc sir but in my android.json file both google_app_id and google_app_key not visible in my file tell me what i do now?
