### ISSUE TITLE
cannot find symbol import by.chemerisuk.cordova.support.ReflectiveCordovaPlugin.ExecutionThread;

### ISSUE THREAD

**Issue by rtm** [chemerisuk/cordova-plugin-firebase-analytics#82]
Building gives me the following error:

```
/home/rtm/repos/nims/blue/cordova/platforms/android/src/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:9: error: cannot find symbol
import by.chemerisuk.cordova.support.ReflectiveCordovaPlugin.ExecutionThread;
                                                            ^
  symbol:   class ExecutionThread
  location: class ReflectiveCordovaPlugin
/home/rtm/repos/nims/blue/cordova/platforms/android/src/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:92: error: cannot find symbol
    @CordovaMethod(ExecutionThread.UI)
                                  ^
  symbol:   method value()
  location: @interface CordovaMethod
/home/rtm/repos/nims/blue/cordova/platforms/android/src/by/chemerisuk/cordova/firebase/FirebaseAnalyticsPlugin.java:92: error: cannot find symbol
    @CordovaMethod(ExecutionThread.UI)
                   ^
  symbol:   variable ExecutionThread
  location: class FirebaseAnalyticsPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.
```

Actually, this error occurs after I manually add an entry to `plugins/android.json` for the plug-in. For some odd reason, that entry was not added automatically when I added the plugin to the project (it was added to browser.json). If I don't add that entry, then the app compiles, but `window.cordova.plugins.firebase.analytics` is not populated, even though the plug-in is referenced correctly in `config.xml` and `package.json` if that matters (it is not listed in `cordova_plugins.js`).

What might account for this?

**Comment by rtm** [comment]
Closing, as I see the problem is lack of support under Cordova Android 6.3 (which I was pinning to due some [other compatibility problems, namely with cordova-plugin-universal-links plugin](https://github.com/walteram/cordova-universal-links-plugin/pull/1), but that's another problem).

**Comment by debby12345** [comment]
error: package by.chemerisuk.cordova.support does not exist import by.chemerisuk.cordova.support.CordovaMethod

I am getting this error when trying to build ionic app in android studio.

**Comment by jrcmadushanka** [comment]
> error: package by.chemerisuk.cordova.support does not exist import by.chemerisuk.cordova.support.CordovaMethod
> 
> I am getting this error when trying to build ionic app in android studio.

Same here

**Comment by jBenes** [comment]
> > error: package by.chemerisuk.cordova.support does not exist import by.chemerisuk.cordova.support.CordovaMethod
> > I am getting this error when trying to build ionic app in android studio.
> 
> Same here

The author has missing dependency here. So installing `cordova-support-android-plugin` should fix it https://github.com/chemerisuk/cordova-support-android-plugin

@debby12345 @jrcmadushanka

**Comment by Gladiatornoshield** [comment]
Hi, I am also experiencing this issue when i tried building on my macbook. on Windows pc it does not have this error. 
I tried installing this cordova-support-android-plugin but no luck. my biggest challenge is that when i have to build for android i have to copy files to windows machine then build and deploy from windows but ios everything is fine.

**Comment by muhammad-gul-dm** [comment]
how to install cordova-support-android-plugin in ionic/capacitor

**Comment by rishi-95** [comment]
> Hi, I am also experiencing this issue when i tried building on my macbook. on Windows pc it does not have this error. I tried installing this cordova-support-android-plugin but no luck. my biggest challenge is that when i have to build for android i have to copy files to windows machine then build and deploy from windows but ios everything is fine.

Facing same issue,

I can see the root of the issue ,
when I did 
npx cap sync

- update android [warn] Plugins are missing dependencies.
       Cordova plugin dependencies must be installed in your project (e.g. w/ npm install).   

       cordova-plugin-firebase-authentication is missing dependencies:
       - cordova-support-android-plugin (~1.0.0)

the plugin is not correctly installed to android folder

@muhammad-gul-dm  any update did you find any solution?

**Comment by marshall86** [comment]
> > > error: package by.chemerisuk.cordova.support does not exist import by.chemerisuk.cordova.support.CordovaMethod
> > > I am getting this error when trying to build ionic app in android studio.
> > 
> > 
> > Same here
> 
> The author has missing dependency here. So installing `cordova-support-android-plugin` should fix it https://github.com/chemerisuk/cordova-support-android-plugin
> 
> @debby12345 @jrcmadushanka

"cordova-support-android-plugin": "^2.0.4" fixed the issue. Life saviour :)
