### ISSUE TITLE
Support for cordova-andriod 6.*

### ISSUE THREAD

**Issue by rtm** [chemerisuk/cordova-plugin-firebase-analytics#84]
I see

    <engine name="cordova-android" version=">=7.0.0"/>

Is there any easy way to make this plugin work under cordova-android 6.*? I have other plugins that are unhappy with 7 and would prefer to stay at 6.

**Comment by rtm** [comment]
I figured out that I would do `cordova plugins add cordova-plugin-firebase-analytics@0.14.0`, but is that going to leave any important 1.0 fixes behind?

**Comment by chemerisuk** [comment]
If you don't need Android < 4.4 - upgrade to cordova-android 7. Old versions are not going to be supported.

**Comment by thesayyn** [comment]
Most of the Cordova plugins has a big problem with cordova-android@7.x. so you cannot force the developers to use 7.x  because we shouldn't be updated just for your plugin
