### ISSUE TITLE
iOS: ld: library not found for -lFirebaseCore

### ISSUE THREAD

**Issue by sahyun1** [chemerisuk/cordova-plugin-firebase-analytics#85]
With this plugin version 1.0 and google-service 1.2,
when running iOS, I get the following error
ld: library not found for -lFirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've done 
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "pwd/Pods/"
pod update
pod setup
pod install
```
none of them solve the issue. any idea?

**Comment by DualH** [comment]
Show me your Podfiel, the mine is like this

`
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'Prex' do
	project 'Prex.xcodeproj'
	pod 'Firebase/Core', '~> 5.0'
end
`

**Comment by DualH** [comment]
Hi @hvaughan3,
When the problem solve, I prefer use **cordova-plugin-firebase**, this plugin include the functionality analytics.

Why use 2 plugins if you can with 1 alone?

Less is better than more 

Regards

**Comment by hvaughan3** [comment]
@DualH That is what I have been using, but it include push notifications which we do not use yet. This is causing Apple to reject the app because we are not registering for push notifications. Are you able to disable push notification code from being added to your build when using that plugin?

**Comment by Menardi** [comment]
It looks like this is a Cordova issue, which happens when installing several plugins at once (such as when restoring from the config file). Installing the pod manually afterwards, as mentioned at https://github.com/phonegap/phonegap-plugin-push/issues/1863#issuecomment-317437829, fixed this for me:

```
cd platforms/ios
pod install
```

**Comment by pavanpaik** [comment]
I am also facing this issue.

Pod update is successful - 
![image](https://user-images.githubusercontent.com/4035808/47260245-8ca28480-d485-11e8-9b98-ef8a496afd32.png)

But I still get an build error as shown below - 
![image](https://user-images.githubusercontent.com/4035808/47260313-41897100-d487-11e8-8c9b-690b8d50d2b5.png)

Here is my Podfile generated by Cordova - 
![image](https://user-images.githubusercontent.com/4035808/47260318-5bc34f00-d487-11e8-8540-06513676eb48.png)

**Comment by ggendre** [comment]
On my side I got the same error but I was trying to build the project on an old device with ios9 but my deployment target was  ios11. I needed to run on an exmulator for xcode to tell me to lower my deployment target...

**Comment by sq-ricardo-pereira** [comment]
Hi guys!
I resolved opening <PROJECT-NAME>.xcworkspace

**Comment by nicolascanto** [comment]
In Build Phases->Link Binary With Libraries-> add FirebaseCore.a

And Done!, This works for me.

**Comment by tiancaipipi110** [comment]
> In Build Phases->Link Binary With Libraries-> add FirebaseCore.a

How did you add the FirebaseCore.a? When I go to my Build Phases ->Link Binary with Libraries, then '+' and search the file, the FirebaseCore.a isn't there.

**Comment by chemerisuk** [comment]
Open platforms/ios/"PROJECT-NAME".xcworkspace

**Comment by veronesecoms** [comment]
i have the same issue... i try all the things in this post

**Comment by sunnykgupta** [comment]
> Hi guys!
> I resolved opening "PROJECT-NAME".xcworkspace

This is the only sane response. 🤣

**Comment by rubenlopezgea** [comment]
> Hi guys!
> I resolved opening "PROJECT-NAME".xcworkspace

Best response.
One detail for dummies like me:
Close all other related XCode windows before.
Then "PROJECT-NAME".xcworkspace takes care of everything.
