### ISSUE TITLE
Error code 65 for command when running via cordova cli

### ISSUE THREAD

**Issue by mcfarljw** [chemerisuk/cordova-plugin-firebase-analytics#87]
I get the following error when trying to use `cordova run ios` from the cli. If I open the project in xcode it runs just fine, but it's more convenient to use cordova with my current build scripts.

```
CompileC /Users/joshua/Library/Developer/Xcode/DerivedData/Skritter-efbrufplvphvojffkmyofkuepxlu/Build/Intermediates.noindex/ArchiveIntermediates/Skritter/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/FirebaseCore.build/Objects-normal/armv7/FIRNetwork.o FirebaseCore/Firebase/Core/FIRNetwork.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

```
(node:99132) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/joshua/Github/skritter/skritter-mobile-v3/cordova/ja/platforms/ios/cordova/build-debug.xcconfig,-workspace,Skritter.xcworkspace,-scheme,Skritter,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,Skritter.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/joshua/Github/skritter/skritter-mobile-v3/cordova/ja/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/joshua/Github/skritter/skritter-mobile-v3/cordova/ja/platforms/ios/build/sharedpch,EMBEDDED_CONTENT_CONTAINS_SWIFT = YES,ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO,LD_RUNPATH_SEARCH_PATHS = "@executable_path/Frameworks"
(node:99132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It looks like it's related to https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/39 which is closed.

Any thoughts?

**Comment by hvaughan3** [comment]
@newuser44 I get hat every time I build now. Once I get that error I go into `/platforms/ios/` and open the xcworkspace file and everything runs fine. Would still be nice to be able to build from the CLI without this error.

I am just using straight Cordova, btw.

**Comment by newuser44** [comment]
Looking at this closer, and was seeing the same thing doing a build in Xcode I'm getting an error about a directory that doesn't exist. 

> ld: warning: directory not found for option '-L/Users/dev/Library/Developer/Xcode/DerivedData/ControlApp-ahjxmgmgyyjzbwehxhuhxtcjidtb/Build/Intermediates.noindex/ArchiveIntermediates/EFS CardControl/BuildProductsPath/Debug-iphoneos/FirebaseCore'
> ld: warning: directory not found for option '-L/Users/dev/Library/Developer/Xcode/DerivedData/ControlApp-ahjxmgmgyyjzbwehxhuhxtcjidtb/Build/Intermediates.noindex/ArchiveIntermediates/EFS CardControl/BuildProductsPath/Debug-iphoneos/GoogleToolboxForMac'
> ld: warning: directory not found for option '-L/Users/dev/Library/Developer/Xcode/DerivedData/ControlApp-ahjxmgmgyyjzbwehxhuhxtcjidtb/Build/Intermediates.noindex/ArchiveIntermediates/ControlApp/BuildProductsPath/Debug-iphoneos/nanopb'
> ld: library not found for -lFirebaseCore
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mcfarljw** [comment]
`cordova run ios` runs `cordova build ios`, so they are probably the same thing and are happening in the build step. I will have to look at my error more closely to see if the path exists or not.

**Comment by hvaughan3** [comment]
@newuser44 I believe I may have fixed my problem by installing the `cordova-plugin-cocoapod-support` plugin and then adding the following element within the iOS `platform` element:

    <preference name="pods_ios_min_version" value="8.0" />

After installing that, rebuilding everything, I think I still had an error, so I closed Xcode, ran `pod install` in `/platforms/ios` and rebuilt and no more errors.

**Comment by mcfarljw** [comment]
I tried and it didn't work, but reverting to a `~> 4.8.1`and things seem to work again. I'm not 100%, but I think the latest versions clash with some cordova stuff. This https://issues.apache.org/jira/browse/CB-10072 and this https://issues.apache.org/jira/browse/CB-10071 in particular.

**Comment by newuser44** [comment]
How do I revert back to 4.8.1?   When you say it works again, you mean no errors and no extra plugins are needed (for cocopods) ?

**Comment by newuser44** [comment]
Probably didn't do this right, changed the package.json to use 4.8.1.  Deleted node_modules and uninstalled ios platform.  Setup node_modules again and add ios platform.  I see it installed firebase plugin.  Getting the same error both in xcode and command line.  Warning directory not found option -L ... /FirebaseCore

**Comment by mcfarljw** [comment]
You shouldn't need to change anything in `package.json` and it looks like the plugin variable doesn't extend to iOS. You will need to manually change things in the `plugin.xml` on this line https://github.com/chemerisuk/cordova-plugin-firebase-analytics/blob/master/plugin.xml#L34

**Comment by newuser44** [comment]
Anybody try just the firebase I guess general plugin?  
https://github.com/arnesson/cordova-plugin-firebase
Sounds like that can do the same things as this one, but more analytics like crashes.

**Comment by hvaughan3** [comment]
@newuser44 The problem with that one is that you must then implement and register for push notifications. Also, that plugin is not compatible with Crashlytics, which will be required for crash reporting on September 8th.

**Comment by newuser44** [comment]
Thanks,  we had plans to implement notifications anyways.   I guess the other plugin could be updated by Sept 8th.   
I still can't get this working with ios.  The folder doesn't exist.   The only thing I haven't tried it is adding in the cordova-plugin-cocoapod-support  plugin.

**Comment by hvaughan3** [comment]
@newuser44 What I finally got working (sort of) is:

- Install `cordova-plugin-firebase-analytics`
- Install `cordova-plugin-cocoapod-support`
- Install `cordova-plugin-ios-frameworks` (only needed to include the AdSupport.framework for iOS)
- Add preference to iOS `platform` element (this may not be needed):
    <preference name="deployment-target" value="8.0" />
- Make sure Cocoa Pods is installed and setup on your machine

- Delete `/platforms` and `/plugins` folders
- `cordova prepare`
  - This will finish saying 0 pods installed
- `cordova prepare`
  - This will finish saying X number of pods installed
- `cd platforms/ios`
- `pod install`
  - For some reason the pods do not actually get installed... I gave up trying to think through this logically
- Now build you cordova project (don't worry if there are errors)
- Now open `.xcworkspace` in `platforms/ios`
- Run the code

**Comment by newuser44** [comment]
With some struggle I'm getting through the steps.  Now I'm getting this while running ionic cordova prepare

```
Installing pods
Sit back and relax this could take a while.
Analyzing dependencies

[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In snapshot (Podfile.lock):
    Firebase/Core (= 5.4.0, ~> 5.0)

  In Podfile:
    Firebase/Core (~> 5.0)

Specs satisfying the `Firebase/Core (~> 5.0), Firebase/Core (= 5.4.0, ~> 5.0)` dependency were found, but they required a higher minimum deployment target.


```

**Comment by hvaughan3** [comment]
@newuser44 I get that too at times but I don't think it has stopped things from working. I did set the firebase cord version in config.xml:

    <variable name="FIREBASE_CORE_VERSION" value="16.0.+" />

Not sure it that has any effect. Also do you have other firebase plugins installed? I also use Crashlytics plugin which causes the mismatch for me.

**Comment by newuser44** [comment]
I added the Firebase version, still got the same error. 
When I do pod install I get the same error that the versions aren't right. 

Did a command line build, it failed. 

Opened up the workspace file, did a build. 

same error as command line. 
'FirebaseCore/FirebaseCore.h' file not found

**Comment by hvaughan3** [comment]
@newuser44 I guess you could try editing the `podfile` and/or `podfile.lock` manually just to see if you can get it working, obviously that not a sustainable solution.

**Comment by chemerisuk** [comment]
[PR with the fix for cordova cli](https://github.com/apache/cordova-ios/pull/398) was merged, so I believe the issue will be resolved in the next cordova-ios release.
