### ISSUE TITLE
I tried building my app in iOS for the first time after having added cordova-plugin-firebase, and I am getting the following error:

### ISSUE THREAD

**Issue by rduvvu** [chemerisuk/cordova-plugin-firebase-analytics#90]
I tried building my app in iOS for the first time after having added cordova-plugin-firebase, and I am getting the following error:

he following build commands failed:
        CompileC /Users/casindia/Library/Developer/Xcode/DerivedData/Jbqwanuodezhltqhaaivbvsnlwdhk/Build/Intermediates.noindex/J\ V.build/Debug-iphonesimulator/J\ V.build/Objects-normal/x86_64/AppDelegate+FirebasePlugin.o J\ V/Plugins/cordova-plugin-firebase/AppDelegate+FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by hvaughan3** [comment]
@rduvvu This is the same or a similar problem to the 4 issues below the one you just created, so check those out.

Until this gets fixed, you can safely ignore this error, open the `/platforms/ios/.xcworkspace` file, and run your app.

**Comment by rduvvu** [comment]
thank u@hvaughan3

**Comment by rduvvu** [comment]
@hvaughan3 
while running the app in xode i am getting this error "*_*Property 'delegate' not found on object of type 'FIRMessaging *'**_"

**Comment by hvaughan3** [comment]
@rduvvu I have not run into that one before unfortunately.

**Comment by kodeine** [comment]
same issue here.

**Comment by kodeine** [comment]
cannot ignore the error if we're running --livereload for ionic

**Comment by suathh** [comment]
It gives Use of undeclared identifier 'FIRAnalyticsConfiguration' error while trying to build with XCode
