### ISSUE TITLE
 FirebaseAnalytics plugin is not installed

### ISSUE THREAD

**Issue by julienkermarec** [chemerisuk/cordova-plugin-firebase-analytics#92]
After installed cordova-plugin-firebase-analytics when i run on android i have this error : 

> Ionic Native: tried calling FirebaseAnalytics.setCurrentScreen, but the FirebaseAnalytics plugin is not installed.
> Install the FirebaseAnalytics plugin: 'ionic cordova plugin add cordova-plugin-firebase-analytics' 

I don't understand, the plugin is installed.

**Comment by thesayyn** [comment]
I'm also facing with this issue
Probably your cordova-android version  is something like 6.x and this plugin doesn't works with 6.x so may you can use an older version of this plugin

**Comment by Leomhl** [comment]
I have the similar issue!


$ ionic cordova plugin add cordova-plugin-firebase-analytics --save


> cordova plugin add cordova-plugin-firebase-analytics --save
Installing "cordova-plugin-firebase-analytics" for android
Installing "cordova-support-android-plugin" for android
Android Studio project detected
	Installing "cordova-support-google-services" for android
Subproject Path: CordovaLib
Subproject Path: app
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-firebase-analytics" for ios
Failed to install 'cordova-plugin-firebase-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/leonardo/Sites/app/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:595:12)
(node:9763) UnhandledPromiseRejectionWarning: Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/leonardo/Sites/app/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:595:12)
(node:9763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9763) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.





My ambient is:


Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, (and 17 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.5.0 (/usr/local/Cellar/node/10.5.0_1/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

**Comment by chemerisuk** [comment]
Try to use the latest version.

**Comment by BinaryBlock** [comment]
Facing similar issue. I believe I am actively using "[latest version](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/releases)" (as of this post):
```
$ cordova plugin ls
call-number 0.0.2 "Cordova Call Number Plugin"
com.lampa.startapp 6.1.6 "startApp"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-calendar 5.1.4 "Calendar"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-fcm-with-dependecy-updated 2.4.0 "Cordova FCM Push Plugin"
cordova-plugin-firebase-analytics 2.0.1 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
```

Any assistance or suggestions would be greatly appreciated. 😄

**Comment by AyoubBoumzebraIonic** [comment]
If you are using IONIC 3, you have to install the lastest version of cordova@9.0.0

**Comment by bioyeneye** [comment]
> If you are using IONIC 3, you have to install the latest version of cordova@9.0.0

this is my ionic info
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0

I am still having the error, any help? Thanks.

**Comment by bioyeneye** [comment]
@AyoubBoumzebraIonic

**Comment by AB91189** [comment]
Native: tried calling FirebaseAnalytics.setCurrentScreen, but the FirebaseAnalytics plugin is not installed

I am getting this warning again and again and no logs coming in my dashboard. Can you please help.
