### ISSUE TITLE
Add support for browser/web platform to be used on progressive web apps

### ISSUE THREAD

**Issue by marcoacevey** [chemerisuk/cordova-plugin-firebase-analytics#96]
Its possible to extend this plugins support for browser/web platform without much effort? We are publishing our ionic app on web as an progressive web app. Depending upon your feedback, we can give help.

**Comment by chemerisuk** [comment]
It's not possible on the web. Firebase analytics is a set of native platform SDKs.

**Comment by marcoacevey** [comment]
Thanks for your feedback!

**Comment by endel** [comment]
More info: https://stackoverflow.com/a/37333205/892698

**Comment by gustavocagninzup** [comment]
@endel  It nows have the support for webapp

https://stackoverflow.com/questions/37330412/how-can-i-use-the-new-firebase-analytics-feature-with-a-webapp
