### ISSUE TITLE
tried calling FirebaseAnalytics.logEvent, but the FirebaseAnalytics plugin is not installed.

### ISSUE THREAD

**Issue by Amadorval75** [chemerisuk/cordova-plugin-firebase-analytics#98]
Hi to all.

I have installed correctly the plugin, on Android it seems to work fine but on iOs I get this message when i call any plugin function.

tried calling FirebaseAnalytics.logEvent, but the FirebaseAnalytics plugin is not installed.

I'm running on XCode 10 and i set the build system already to legacy (because fcm problem that i solved like this)

This problem seems to appear since I updated xcode, but I don't know what is happening now.

Some help??

**Comment by Amadorval75** [comment]
Any help on this???

**Comment by Amadorval75** [comment]
Hi anyone kwons any plugin to use instead this plugin? I think this development is abandoned, no one answers......

**Comment by NaveenSubburaj** [comment]
Any update on this?

**Comment by BinaryBlock** [comment]
Why was this issue closed? I am facing same problem and looking for a solution.

**Comment by yaro08** [comment]
me too...

**Comment by SergioZhydecky** [comment]
I have the same issue

**Comment by SergioZhydecky** [comment]
Anyone know solution ?

**Comment by davidmhHuenei** [comment]
I have the same issue

**Comment by viettran-dht** [comment]
@davidmhHuenei 
I found solution, try update cordova to ver 9
npm uninstall -g cordova
npm install -g cordova@9.0.0
