### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by jayvillao** [chemerisuk/cordova-plugin-firebase-analytics#99]
I have successfully installed the plugin and automatic events logger is running fine, I can see logs in Firebase console.

Although, when I try to log a custom Event, this error happens like the injector isn't finding the lib correctly to inject in the service file.

Anybody has any idea on this? please:

Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at one-one-module.js:178
    at Module../node_modules/@ionic-native/firebase-analytics/index.js (one-one-module.js:242)
    at __webpack_require__ (runtime.js:84)
    at Module../src/app/one/one.page.ts (one-one-module.js:336)
    at __webpack_require__ (runtime.js:84)

**Comment by pjc0247** [comment]
I think this issue related to ionic v4

**Comment by deissh** [comment]
Resolved, please use this
https://beta.ionicframework.com/docs/native/firebase-analytics/

**Comment by saberprashant** [comment]
Hey @chemerisuk @jayvillao , I am facing the similar problem, please help.  

Error is-
```
ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at FirebaseAnalytics.logEvent (vendor.js:102827)
    at MyApp.webpackJsonp.853.MyApp.registerFA (main.js:8375)
    at main.js:8239
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4509)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4500)
    at FirebaseAnalytics.logEvent (vendor.js:102827)
    at MyApp.webpackJsonp.853.MyApp.registerFA (main.js:8375)
    at main.js:8239
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4509)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4500)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4500)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
```

**Comment by saberprashant** [comment]
Hey @bpvani @pjc0247 , can you help me in this as I am getting a similar problem and I am using Ionic 2.
Thanks

**Comment by chemerisuk** [comment]
Problems with ionic, but not this plugin.

**Comment by saberprashant** [comment]
Hey @chemerisuk , thanks for replying. If this issue is with ionic, then how can I resolve it? Any pointers would be really helpful.

Thanks :)

**Comment by chemerisuk** [comment]
Try to start with  https://stackoverflow.com/questions/50348643/typeerror-object-is-not-a-function

Sorry, I don't have experience with ionic.

**Comment by saberprashant** [comment]
Hey,

I found a solution to this problem, 
Actually the ```npm``` package for ```firebase-analytics``` was causing the problem.
I installed the latest with this command : 
```
npm install @ionic-native/firebase-analytics
```
Due to this, latest version (5.x.x) was installed and it requires to have a setup of ionic v4, with rxjs@6.

So, I downgraded the version of that package:
```
npm install @ionic-native/firebase-analytics@4
```

With this, version 4.x.x will be installed which will work perfectly with the ionic v3.

**Comment by light8822** [comment]
Does anyone found the right way to solve this issue?

**Comment by santiagovasquez** [comment]
I need help ......
**run** npm install @ionic-native/firebase-analytics@4

package.json
->     "@ionic-native/firebase-analytics": "^4.20.0",
-> "cordova-plugin-firebase-analytics": "^3.0.0",

return error 
`Error: Uncaught (in promise): TypeError: this.firebaseAnalytics.logEvent('pages', { param1: "vista_LoginCliente" }) .then is not a function. (In 'this.firebaseAnalytics.logEvent('pages', { param1: "vista_LoginCliente" }) .then(function (res) { return console.log(res, ' 11111111'); })', 'this.firebaseAnalytics.logEvent('pages', { param1: "vista_LoginCliente" }) .then' is undefined) LoginClientPage@http://localhost:8080/build/main.js:2346:18 LoginClientPage@[native code] createClass@http://localhost:8080/build/vendor.js:12865:75 createDirectiveInstance@http://localhost:8080/build/vendor.js:12700:48 createViewNodes@http://localhost:8080/build/vendor.js:14158:76 createRootView@http://localhost:8080/build/vendor.js:14047:20 callWithDebugContext@http://localhost:8080/build/vendor.js:15472:47 create@http://localhost:8080/build/vendor.js:11652:60 _viewInit@http://localhost:8080/build/vendor.js:53971:50 http://localhost:8080/build/vendor.js:53784:32 onInvoke@http://localhost:8080/build/vendor.js:5134:39 run@http://localhost:8080/build/polyfills.js:3:10149 http://localhost:8080/build/polyfills.js:3:20245 onInvokeTask@http://localhost:8080/build/vendor.js:5125:43 runTask@http://localhost:8080/build/polyfills.js:3:10844 o@http://localhost:8080/build/polyfills.js:3:7901 invokeTask@http://localhost:8080/build/polyfills.js:3:16824 p@http://localhost:8080/build/polyfills.js:2:27654 v@http://localhost:8080/build/polyfills.js:2:27894
c — polyfills.js:3:19762
(anonymous function) — polyfills.js:3:19176
_fireError — nav-controller-base.js:223
_failed — nav-controller-base.js:216
onInvoke — core.js:4760
run — polyfills.js:3:10150
(anonymous function) — polyfills.js:3:20246
onInvokeTask — core.js:4751
runTask — polyfills.js:3:10845
o — polyfills.js:3:7902
invokeTask — polyfills.js:3:16825
p — polyfills.js:2:27655
v — polyfills.js:2:27895`

**Comment by r4ugust** [comment]
> I need help ......
> **run** npm install @ionic-native/firebase-analytics@4
> 
> package.json
> -> "@ionic-native/firebase-analytics": "^4.20.0",
> -> "cordova-plugin-firebase-analytics": "^3.0.0",
> 
> return error
> `Error: Uncaught (in promise): TypeError: this.firebaseAnalytics.logEvent('pages', { param1: "vista_LoginCliente" }) .then is not a function. (In 'this.firebaseAnalytics.logEvent('pages', { param1: "vista_LoginCliente" }) .then(function (res) { return console.log(res, ' 11111111'); })', 'this.firebaseAnalytics.logEvent('pages', { param1: "vista_LoginCliente" }) .then' is undefined) LoginClientPage@http://localhost:8080/build/main.js:2346:18 LoginClientPage@[native code] createClass@http://localhost:8080/build/vendor.js:12865:75 createDirectiveInstance@http://localhost:8080/build/vendor.js:12700:48 createViewNodes@http://localhost:8080/build/vendor.js:14158:76 createRootView@http://localhost:8080/build/vendor.js:14047:20 callWithDebugContext@http://localhost:8080/build/vendor.js:15472:47 create@http://localhost:8080/build/vendor.js:11652:60 _viewInit@http://localhost:8080/build/vendor.js:53971:50 http://localhost:8080/build/vendor.js:53784:32 onInvoke@http://localhost:8080/build/vendor.js:5134:39 run@http://localhost:8080/build/polyfills.js:3:10149 http://localhost:8080/build/polyfills.js:3:20245 onInvokeTask@http://localhost:8080/build/vendor.js:5125:43 runTask@http://localhost:8080/build/polyfills.js:3:10844 o@http://localhost:8080/build/polyfills.js:3:7901 invokeTask@http://localhost:8080/build/polyfills.js:3:16824 p@http://localhost:8080/build/polyfills.js:2:27654 v@http://localhost:8080/build/polyfills.js:2:27894 c — polyfills.js:3:19762 (anonymous function) — polyfills.js:3:19176 _fireError — nav-controller-base.js:223 _failed — nav-controller-base.js:216 onInvoke — core.js:4760 run — polyfills.js:3:10150 (anonymous function) — polyfills.js:3:20246 onInvokeTask — core.js:4751 runTask — polyfills.js:3:10845 o — polyfills.js:3:7902 invokeTask — polyfills.js:3:16825 p — polyfills.js:2:27655 v — polyfills.js:2:27895`

@santiagovasquez, that's because it's ionic-native. It won't work unless it's running in the simulator or the real device.

See this explanation: https://stackoverflow.com/questions/54321622/ionic-runtime-error-this-fba-logevent-then-is-not-a-function
